# This file is auto-generated by alef. DO NOT EDIT.
"""Configuration options for the conversion API."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ImageDetail(str, Enum):
    """Image detail."""

    LOW = "low"
    HIGH = "high"
    AUTO = "auto"


class ToolType(str, Enum):
    """The type discriminator for tool/tool-call objects. Per the OpenAI spec this."""

    FUNCTION = "function"


class FinishReason(str, Enum):
    """Why a choice stopped generating tokens."""

    STOP = "stop"
    LENGTH = "length"
    TOOL_CALLS = "tool_calls"
    CONTENT_FILTER = "content_filter"
    FUNCTION_CALL = "function_call"
    OTHER = "other"


class ReasoningEffort(str, Enum):
    """Controls how much reasoning effort the model should use."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class FunctionCall:
    """Placeholder for FunctionCall type."""


@dataclass
class SystemMessage:
    """System message."""

    content: str = ""
    name: str | None = None


@dataclass
class UserMessage:
    """User message."""

    content: dict[str, Any] | None = None
    name: str | None = None


@dataclass
class ImageUrl:
    """Image url."""

    url: str = ""
    detail: str | None = None


@dataclass
class DocumentContent:
    """Document content."""

    data: str = ""
    """Base64-encoded document data or URL."""

    media_type: str = ""
    """MIME type (e.g., "application/pdf", "text/csv")."""


@dataclass
class AudioContent:
    """Audio content."""

    data: str = ""
    """Base64-encoded audio data."""

    format: str = ""
    """Audio format (e.g., "wav", "mp3", "ogg")."""


@dataclass
class AssistantMessage:
    """Assistant message."""

    content: str | None = None
    name: str | None = None
    tool_calls: list[Any] | None = None
    refusal: str | None = None
    function_call: Any | None = None
    """Deprecated legacy function_call field; retained for API compatibility."""


@dataclass
class ToolMessage:
    """Tool message."""

    content: str = ""
    tool_call_id: str = ""
    name: str | None = None


@dataclass
class DeveloperMessage:
    """Developer message."""

    content: str = ""
    name: str | None = None


@dataclass
class FunctionMessage:
    """Deprecated legacy function-role message body."""

    content: str = ""
    name: str = ""


@dataclass
class SpecificToolChoice:
    """Specific tool choice."""

    choice_type: str = "function"
    function: Any | None = None


@dataclass
class SpecificFunction:
    """Specific function."""

    name: str = ""


@dataclass
class JsonSchemaFormat:
    """Json schema format."""

    name: str = ""
    description: str | None = None
    schema: str = ""
    strict: bool | None = None


@dataclass
class Usage:
    """Usage."""

    prompt_tokens: int = 0
    """Prompt tokens used. Defaults to 0 when absent (some providers omit this)."""

    completion_tokens: int = 0
    """Completion tokens used. Defaults to 0 when absent (e.g. embedding responses)."""

    total_tokens: int = 0
    """Total tokens used. Defaults to 0 when absent (some providers omit this)."""


@dataclass
class ChatCompletionRequest:
    """Chat completion request."""

    model: str = ""
    messages: list[dict[str, Any]] = field(default_factory=list)
    temperature: float | None = None
    top_p: float | None = None
    n: int | None = None
    stream: bool | None = None
    """Whether to stream the response."""

    stop: dict[str, Any] | None = None
    max_tokens: int | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    logit_bias: dict[str, float] | None = None
    """Token bias map.  Uses `BTreeMap` (sorted keys) for deterministic"""

    user: str | None = None
    tools: list[Any] | None = None
    tool_choice: dict[str, Any] | None = None
    parallel_tool_calls: bool | None = None
    response_format: dict[str, Any] | None = None
    stream_options: Any | None = None
    seed: int | None = None
    reasoning_effort: str | None = None
    extra_body: str | None = None
    """Provider-specific extra parameters merged into the request body."""


@dataclass
class StreamOptions:
    """Stream options."""

    include_usage: bool | None = None


@dataclass
class ChatCompletionResponse:
    """Chat completion response."""

    id: str = ""
    object: str = ""
    """Always `"chat.completion"` from OpenAI-compatible APIs.  Stored as a"""

    created: int = 0
    model: str = ""
    choices: list[Any] = field(default_factory=list)
    usage: Any | None = None
    system_fingerprint: str | None = None
    service_tier: str | None = None


@dataclass
class Choice:
    """Choice."""

    index: int = 0
    message: Any | None = None
    finish_reason: str | None = None


@dataclass
class ChatCompletionChunk:
    """Chat completion chunk."""

    id: str = ""
    object: str = ""
    """Always `"chat.completion.chunk"` from OpenAI-compatible APIs.  Stored"""

    created: int = 0
    model: str = ""
    choices: list[Any] = field(default_factory=list)
    usage: Any | None = None
    system_fingerprint: str | None = None
    service_tier: str | None = None


@dataclass
class StreamChoice:
    """Stream choice."""

    index: int = 0
    delta: Any | None = None
    finish_reason: str | None = None


@dataclass
class StreamDelta:
    """Stream delta."""

    role: str | None = None
    content: str | None = None
    tool_calls: list[Any] | None = None
    function_call: Any | None = None
    """Deprecated legacy function_call delta; retained for API compatibility."""

    refusal: str | None = None


@dataclass
class StreamToolCall:
    """Stream tool call."""

    index: int = 0
    id: str | None = None
    call_type: str | None = None
    function: Any | None = None


@dataclass
class StreamFunctionCall:
    """Stream function call."""

    name: str | None = None
    arguments: str | None = None


@dataclass
class CreateImageRequest:
    """Request to create images from a text prompt."""

    prompt: str = ""
    model: str | None = None
    n: int | None = None
    size: str | None = None
    quality: str | None = None
    style: str | None = None
    response_format: str | None = None
    user: str | None = None


@dataclass
class ImagesResponse:
    """Response containing generated images."""

    created: int = 0
    data: list[Any] = field(default_factory=list)


@dataclass
class Image:
    """A single generated image, returned as either a URL or base64 data."""

    url: str | None = None
    b64_json: str | None = None
    revised_prompt: str | None = None


@dataclass
class CreateSpeechRequest:
    """Request to generate speech audio from text."""

    model: str = ""
    input: str = ""
    voice: str = ""
    response_format: str | None = None
    speed: float | None = None


@dataclass
class CreateTranscriptionRequest:
    """Request to transcribe audio into text."""

    model: str = ""
    file: str = ""
    """Base64-encoded audio file data."""

    language: str | None = None
    prompt: str | None = None
    response_format: str | None = None
    temperature: float | None = None


@dataclass
class TranscriptionResponse:
    """Response from a transcription request."""

    text: str = ""
    language: str | None = None
    duration: float | None = None
    segments: list[Any] | None = None


@dataclass
class TranscriptionSegment:
    """A segment of transcribed audio with timing information."""

    id: int = 0
    start: float = 0.0
    end: float = 0.0
    text: str = ""


@dataclass
class SearchRequest:
    """A search request."""

    model: str = ""
    """The model/provider to use (e.g. `"brave/web-search"`, `"tavily/search"`)."""

    query: str = ""
    """The search query."""

    max_results: int | None = None
    """Maximum number of results to return."""

    search_domain_filter: list[str] | None = None
    """Domain filter — restrict results to specific domains."""

    country: str | None = None
    """Country code for localized results (ISO 3166-1 alpha-2)."""


@dataclass
class ModelsListResponse:
    """Models list response."""

    object: str = ""
    """Always `"list"` from OpenAI-compatible APIs.  Stored as a plain"""

    data: list[Any] = field(default_factory=list)


@dataclass
class ModelObject:
    """Model object."""

    id: str = ""
    object: str = ""
    """Always `"model"` from OpenAI-compatible APIs.  Stored as a plain"""

    created: int = 0
    owned_by: str = ""
