# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
defmodule LiterLlmE2E.BudgetTest do
  use ExUnit.Case, async: true

  alias LiterLlmE2E.MockServer
  alias LiterLlmE2E.Helpers

  test "Tests that a request is rejected when budget is exceeded" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: "{}",
        stream_chunks: []
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    client =
      LiterLlm.client(
        api_key: "test-key",
        base_url: base_url,
        max_retries: 0,
        budget: [global_limit: 0.0, enforcement: :hard]
      )

    assert {:error, %LiterLlm.BudgetExceededError{}} =
             LiterLlm.chat(
               client,
               "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}"
             )
  end

  test "Tests per-model budget limit" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: "{}",
        stream_chunks: []
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    client =
      LiterLlm.client(
        api_key: "test-key",
        base_url: base_url,
        max_retries: 0,
        budget: [enforcement: :hard, model_limits: Jason.decode!("{\"gpt-4\":0.0}")]
      )

    assert {:error, %LiterLlm.BudgetExceededError{}} =
             LiterLlm.chat(
               client,
               "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}"
             )
  end

  test "Tests that cost is tracked after a successful response" do
    routes = [
      %{
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body:
          "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello! How can I help you today?\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-budget-tracked-001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":9,\"prompt_tokens\":8,\"total_tokens\":17}}",
        stream_chunks: []
      }
    ]

    {:ok, base_url} = MockServer.start(routes)

    client = LiterLlm.client(api_key: "test-key", base_url: base_url, max_retries: 0, budget: [])

    {:ok, resp} =
      LiterLlm.chat(
        client,
        "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}"
      )

    assert resp != nil
    # Verify cost was tracked after the request
    assert LiterLlm.Budget.global_spend() > 0, "Expected cost to be tracked"
  end
end
