// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: configuration.</summary>
public class ConfigurationTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_CustomBaseUrl()
    {
        // Client configured with a custom base URL routes all requests to that endpoint
        var result = await LiterLlmLib.Chat(null);
        // TODO: unsupported assertion type: count_equals
        Assert.Equal("Hi there!", result.Choices["0"].Message.Content.Trim());
        Assert.Equal("stop", result.Choices["0"].FinishReason.Trim());
        Assert.Equal("local-model", result.Model.Trim());
    }

    [Fact]
    public async Task Test_ExtraHeaders()
    {
        // Client configured with extra custom headers successfully completes a chat request
        var result = await LiterLlmLib.Chat(null);
        // TODO: unsupported assertion type: count_equals
        Assert.Equal("stop", result.Choices["0"].FinishReason.Trim());
    }

    [Fact]
    public async Task Test_LocalProviderLlamacpp()
    {
        // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
        var result = await LiterLlmLib.Chat(null);
        // TODO: unsupported assertion type: count_equals
        Assert.Equal("Hi there! I'm running locally.", result.Choices["0"].Message.Content.Trim());
        Assert.Equal("stop", result.Choices["0"].FinishReason.Trim());
        Assert.Equal("my-model", result.Model.Trim());
    }

    [Fact]
    public async Task Test_LocalProviderOllama()
    {
        // Ollama local provider routes requests via ollama/ model prefix with no auth
        var result = await LiterLlmLib.Chat(null);
        // TODO: unsupported assertion type: count_equals
        Assert.Equal("Hello! How can I help you today?", result.Choices["0"].Message.Content.Trim());
        Assert.Equal("stop", result.Choices["0"].FinishReason.Trim());
        Assert.Equal("qwen2:0.5b", result.Model.Trim());
    }

    [Fact]
    public async Task Test_LocalProviderVllm()
    {
        // vLLM local provider routes requests via vllm/ model prefix with no auth
        var result = await LiterLlmLib.Chat(null);
        // TODO: unsupported assertion type: count_equals
        Assert.Equal("Hello! How may I assist you?", result.Choices["0"].Message.Content.Trim());
        Assert.Equal("stop", result.Choices["0"].FinishReason.Trim());
        Assert.Equal("meta-llama/Llama-3.2-1B", result.Model.Trim());
    }
}
