// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: contract.</summary>
public class ContractTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_BindingApiParity()
    {
        // Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
        var result = await LiterLlmLib.Chat(null);
        // TODO: unsupported assertion type: count_equals
        Assert.Equal("OK", result.Choices["0"].Message.Content.Trim());
        Assert.Equal("stop", result.Choices["0"].FinishReason.Trim());
        Assert.Equal(6, result.Usage.TotalTokens);
        Assert.Equal("gpt-4o", result.Model.Trim());
    }

    [Fact]
    public async Task Test_ContractOcr()
    {
        // Verify ocr() method exists in all bindings
        var result = await LiterLlmLib.Chat(null);
    }

    [Fact]
    public async Task Test_ContractSearch()
    {
        // Verify search() method exists in all bindings
        var result = await LiterLlmLib.Chat(null);
    }
}
