# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'liter_llm'
require 'json'

RSpec.describe 'contract' do
  it 'binding_api_parity: Verify all bindings expose the full API surface — constructor accepts all config options and every method exists' do
    result = LiterLlm.chat(nil)
    # TODO: unsupported assertion type: count_equals
    expect(result.choices.get("0").message.content).to eq('OK')
    expect(result.choices.get("0").finish_reason).to eq('stop')
    expect(result.usage.total_tokens).to eq(6)
    expect(result.model).to eq('gpt-4o')
  end

  it 'contract_ocr: Verify ocr() method exists in all bindings' do
    result = LiterLlm.chat(nil)
    expect(result).not_to be_nil
  end

  it 'contract_search: Verify search() method exists in all bindings' do
    result = LiterLlm.chat(nil)
    expect(result).not_to be_nil
  end
end
