// Code generated by alef. DO NOT EDIT.

// E2e tests for category: files
package e2e_test

import (
	"testing"

	pkg "liter_llm"
)

func Test_EdgeFileEmptyList(t *testing.T) {
	// List files when no files have been uploaded
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	// TODO: unsupported assertion type: count_equals
}

func Test_EdgeFileLargeUpload(t *testing.T) {
	// Upload a large file successfully
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Id) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_ErrorFileAuth401(t *testing.T) {
	// 401 Unauthorized when listing files with invalid API key
	_, err := pkg.chat(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorFileBadPurpose(t *testing.T) {
	// 400 Bad Request when uploading a file with invalid purpose
	_, err := pkg.chat(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ErrorFileNotFound(t *testing.T) {
	// 404 Not Found when retrieving a nonexistent file
	_, err := pkg.chat(nil)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_SmokeCreateFile(t *testing.T) {
	// Upload a file for use with the API
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Id) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_SmokeDeleteFile(t *testing.T) {
	// Delete an uploaded file
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Id) == 0 {
		t.Errorf("expected non-empty value")
	}
	if result.Deleted != true {
		t.Errorf("equals mismatch: got %v", result.Deleted)
	}
}

func Test_SmokeFileContent(t *testing.T) {
	// Retrieve the content of an uploaded file
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Content) == 0 {
		t.Errorf("expected non-empty value")
	}
}

func Test_SmokeListFiles(t *testing.T) {
	// List all uploaded files
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	// TODO: unsupported assertion type: count_equals
}

func Test_SmokeRetrieveFile(t *testing.T) {
	// Retrieve metadata for an uploaded file
	result, err := pkg.chat(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Id) == 0 {
		t.Errorf("expected non-empty value")
	}
}
