// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: cache

use liter_llm::{chat, chat_stream};
mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_cache_hit() {
    // Tests that identical chat requests return cached response
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-cache-hit-001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(&request).await.expect("should succeed");
    assert!(result.cache_hit, "expected true");
}

#[tokio::test]
async fn test_cache_miss_ttl() {
    // Tests that cache expires after TTL
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-cache-miss-001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(&request).await.expect("should succeed");
    assert!(result.cache_hit, "expected true");
}

#[tokio::test]
async fn test_cache_opendal_memory() {
    // Cache hit with OpenDAL memory backend returns cached response on repeat request
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-opendal-mem-001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":2,"prompt_tokens":5,"total_tokens":7}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(&request).await.expect("should succeed");
    assert!(result.cache_hit, "expected true");
}

#[tokio::test]
async fn test_cache_stream_bypass() {
    // Tests that streaming requests bypass cache entirely
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-stream-bypass-001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat_stream(&request).await.expect("should succeed");
    assert!(result.cache_bypassed, "expected true");
}

