// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: custom_provider

use liter_llm::chat;
mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_provider_auth() {
    // Tests custom provider with custom auth header
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello with custom auth!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-auth-001","model":"my-auth-model-v1","object":"chat.completion","usage":{"completion_tokens":6,"prompt_tokens":8,"total_tokens":14}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let _ = chat(request).await.expect("should succeed");
}

#[tokio::test]
async fn test_register_provider() {
    // Tests that a custom provider can be registered and routes requests
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello from custom provider!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-custom-001","model":"my-model-v1","object":"chat.completion","usage":{"completion_tokens":7,"prompt_tokens":8,"total_tokens":15}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let _ = chat(request).await.expect("should succeed");
}

