// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: proxy

use liter_llm::chat;
mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_proxy_auth_invalid() {
    // 401 Unauthorized when an invalid API key is provided through the proxy
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 401,
        body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided: sk-invalid. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await;
    assert!(result.is_err(), "expected call to fail");
    assert!(result.as_ref().unwrap_err().to_string().contains("Authentication"), "error message mismatch");
}

#[tokio::test]
async fn test_proxy_auth_missing() {
    // 401 Unauthorized when no API key is provided through the proxy
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 401,
        body: r#"{"error":{"code":null,"message":"You didn't provide an API key. You need to provide your API key in an Authorization header.","param":null,"type":"invalid_request_error"}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await;
    assert!(result.is_err(), "expected call to fail");
    assert!(result.as_ref().unwrap_err().to_string().contains("Authentication"), "error message mismatch");
}

#[tokio::test]
async fn test_proxy_chat_basic() {
    // Basic chat completion request routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-proxy001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":3,"prompt_tokens":10,"total_tokens":13}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    // TODO: unsupported assertion type: count_equals
    assert_eq!(result.choices.get("0").map(|s| s.as_str()).message.content.trim(), r#"Hello!"#, "equals assertion failed");
    assert_eq!(result.choices.get("0").map(|s| s.as_str()).finish_reason.trim(), r#"stop"#, "equals assertion failed");
}

#[tokio::test]
async fn test_proxy_chat_streaming() {
    // Streaming chat completion routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 200,
        body: String::new(),
        stream_chunks: vec![
            r#"{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}"#.to_string(),
            r#"{"choices":[{"delta":{"content":"1"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}"#.to_string(),
            r#"{"choices":[{"delta":{"content":" 2"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}"#.to_string(),
            r#"{"choices":[{"delta":{"content":" 3"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}"#.to_string(),
            r#"{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}"#.to_string(),
        ],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    assert!(result.chunks.len() >= 3, "expected at least 3 elements, got {}", result.chunks.len());
    assert_eq!(result.stream_content.trim(), r#"1 2 3"#, "equals assertion failed");
    // TODO: unsupported assertion type: is_true
}

#[tokio::test]
async fn test_proxy_embeddings() {
    // Embedding request routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/embeddings",
        method: "POST",
        status: 200,
        body: r#"{"data":[{"embedding":[0.01,0.02,0.03,0.04,0.05],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!("Hello world");
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    // TODO: unsupported assertion type: count_equals
}

#[tokio::test]
async fn test_proxy_health() {
    // Health check verifying proxy connectivity via list models
    let mock_route = MockRoute {
        path: "/v1/models",
        method: "POST",
        status: 200,
        body: r#"{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"}],"object":"list"}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    assert!(!result.data.is_empty(), "expected >= 1");
}

#[tokio::test]
async fn test_proxy_image_generate() {
    // Image generation request routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/images/generations",
        method: "POST",
        status: 200,
        body: r#"{"created":1711000000,"data":[{"revised_prompt":"A vivid sunset casting warm orange and pink hues over a calm ocean","url":"https://example.com/images/img-proxy001.png"}]}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    // TODO: unsupported assertion type: count_equals
    assert!(!result.data.get("0").map(|s| s.as_str()).url.is_empty(), "expected non-empty value");
}

#[tokio::test]
async fn test_proxy_models_list() {
    // List models request routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/models",
        method: "POST",
        status: 200,
        body: r#"{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"},{"created":1721172741,"id":"gpt-4o-mini","object":"model","owned_by":"openai"}],"object":"list"}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    assert!(!result.data.is_empty(), "expected >= 1");
}

#[tokio::test]
async fn test_proxy_moderation() {
    // Content moderation request routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/moderations",
        method: "POST",
        status: 200,
        body: r#"{"id":"modr-proxy001","model":"omni-moderation-latest","results":[{"categories":{"harassment":false,"harassment/threatening":false,"hate":false,"hate/threatening":false,"self-harm":false,"self-harm/instructions":false,"self-harm/intent":false,"sexual":false,"sexual/minors":false,"violence":false,"violence/graphic":false},"category_scores":{"harassment":0.0002,"harassment/threatening":0.0001,"hate":0.0001,"hate/threatening":0.0001,"self-harm":0.0001,"self-harm/instructions":0.0001,"self-harm/intent":0.0001,"sexual":0.0001,"sexual/minors":0.0001,"violence":0.0001,"violence/graphic":0.0001},"flagged":false}]}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!("The weather is nice today.");
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    // TODO: unsupported assertion type: count_equals
    assert!(!result.results.get("0").map(|s| s.as_str()).flagged, "equals assertion failed");
}

#[tokio::test]
async fn test_proxy_rerank() {
    // Document reranking request routed through the proxy
    let mock_route = MockRoute {
        path: "/v1/rerank",
        method: "POST",
        status: 200,
        body: r#"{"id":"rerank-proxy001","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.95},{"index":1,"relevance_score":0.03}]}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    // TODO: unsupported assertion type: count_equals
    assert!(result.results.get("0").map(|s| s.as_str()).relevance_score > 0.9_f64, "expected > 0.9_f64");
}

#[tokio::test]
async fn test_proxy_upstream_429() {
    // 429 Too Many Requests from upstream provider through the proxy
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 429,
        body: r#"{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4o in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await;
    assert!(result.is_err(), "expected call to fail");
    assert!(result.as_ref().unwrap_err().to_string().contains("RateLimited"), "error message mismatch");
}

#[tokio::test]
async fn test_proxy_upstream_500() {
    // 500 Internal Server Error from upstream provider through the proxy
    let mock_route = MockRoute {
        path: "/v1/chat/completions",
        method: "POST",
        status: 500,
        body: r#"{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await;
    assert!(result.is_err(), "expected call to fail");
    assert!(result.as_ref().unwrap_err().to_string().contains("ServerError"), "error message mismatch");
}

