// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[path = "mock_server.rs"]
mod mock_server;

use liter_llm::{ClientConfigBuilder, DefaultClient, LlmClient};

/// 401 Authentication error returned by the Anthropic API when the API key is invalid
#[tokio::test]
async fn anthropic_error_auth() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 401,
        body: r#"{"error":{"message":"invalid x-api-key","type":"authentication_error"},"type":"error"}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest = serde_json::from_str(
        r#"{"messages":[{"content":"Hello","role":"user"}],"model":"anthropic/claude-3-5-sonnet-20241022"}"#,
    )
    .unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::Authentication { .. }),
        "Expected Authentication error"
    );

    server.shutdown();
}

/// 401 Unauthorized error when API key is invalid or missing
#[tokio::test]
async fn auth_401() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 401,
            body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::Authentication { .. }),
        "Expected Authentication error"
    );

    server.shutdown();
}

/// Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied
#[tokio::test]
async fn azure_error_auth() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 401,
            body: r#"{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.","param":null,"type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"azure/gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::Authentication { .. }),
        "Expected Authentication error"
    );

    server.shutdown();
}

/// 400 Bad Request error when a parameter value is invalid
#[tokio::test]
async fn bad_request_400() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 400,
            body: r#"{"error":{"message":"Invalid parameter: temperature must be between 0 and 2","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4","temperature":5.0}"#)
            .unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(
            result.unwrap_err(),
            liter_llm::LiterLlmError::BadRequest { .. }
                | liter_llm::LiterLlmError::ContextWindowExceeded { .. }
                | liter_llm::LiterLlmError::ContentPolicy { .. }
        ),
        "Expected 400-class error"
    );

    server.shutdown();
}

/// AWS Bedrock returns 403 Forbidden (not 401) when credentials are missing, expired, or the IAM role lacks bedrock:InvokeModel permission — verifies the error is mapped to Authentication
#[tokio::test]
async fn bedrock_error_auth() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 403,
        body: r#"{"message":"You don't have access to the model with the specified model ID."}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest = serde_json::from_str(
        r#"{"messages":[{"content":"Hello","role":"user"}],"model":"bedrock/anthropic.claude-3-sonnet-20240229-v1:0"}"#,
    )
    .unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    let _ = result.unwrap_err();

    server.shutdown();
}

/// 400 error when a request is rejected due to content policy
#[tokio::test]
async fn content_policy_violation() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 400,
            body: r#"{"error":{"message":"Your request was rejected as a result of our content_policy","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Generate harmful content","role":"user"}],"model":"gpt-4"}"#)
            .unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(
            result.unwrap_err(),
            liter_llm::LiterLlmError::BadRequest { .. }
                | liter_llm::LiterLlmError::ContextWindowExceeded { .. }
                | liter_llm::LiterLlmError::ContentPolicy { .. }
        ),
        "Expected 400-class error"
    );

    server.shutdown();
}

/// 400 error when the prompt exceeds the model's maximum context length
#[tokio::test]
async fn context_window_exceeded() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 400,
            body: r#"{"error":{"code":"context_length_exceeded","message":"This model's maximum context length is 8192 tokens","type":"invalid_request_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest = serde_json::from_str(r#"{"messages":[{"content":"Very long prompt that exceeds the context window...","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(
            result.unwrap_err(),
            liter_llm::LiterLlmError::BadRequest { .. }
                | liter_llm::LiterLlmError::ContextWindowExceeded { .. }
                | liter_llm::LiterLlmError::ContentPolicy { .. }
        ),
        "Expected 400-class error"
    );

    server.shutdown();
}

/// 403 Forbidden error when the API key does not have access to the requested resource
#[tokio::test]
async fn forbidden_403() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 403,
        body: r#"{"error":{"message":"Access denied","type":"access_denied"}}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    let _ = result.unwrap_err();

    server.shutdown();
}

/// 504 Gateway Timeout error when the upstream service times out
#[tokio::test]
async fn gateway_timeout_504() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 504,
        body: r#"{"error":{"message":"Gateway timeout","type":"server_error"}}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    let _ = result.unwrap_err();

    server.shutdown();
}

/// 404 Not Found error when requesting a model that does not exist
#[tokio::test]
async fn not_found_404() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 404,
        body: r#"{"error":{"message":"Model not found","type":"not_found_error"}}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-99"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::NotFound { .. }),
        "Expected NotFound error"
    );

    server.shutdown();
}

/// 429 Too Many Requests error when the rate limit is exceeded
#[tokio::test]
async fn rate_limit_429() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 429,
            body: r#"{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::RateLimited { .. }),
        "Expected RateLimited error"
    );

    server.shutdown();
}

/// 500 Internal Server Error from the upstream API
#[tokio::test]
async fn server_error_500() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 500,
            body: r#"{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::ServerError { .. }),
        "Expected ServerError error"
    );

    server.shutdown();
}

/// 502 Bad Gateway error when the upstream service is unavailable
#[tokio::test]
async fn service_unavailable_502() {
    let server = mock_server::MockServer::start(vec![mock_server::MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 502,
        body: r#"{"error":{"message":"Bad gateway","type":"server_error"}}"#.to_string(),
        stream_chunks: vec![],
    }])
    .await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::ServiceUnavailable { .. }),
        "Expected ServiceUnavailable error"
    );

    server.shutdown();
}

/// Google Vertex AI returns 401 Unauthorized when the OAuth2 token is missing, expired, or the service account lacks aiplatform.endpoints.predict permission — verifies the error is mapped to Authentication
#[tokio::test]
async fn vertex_error_auth() {
    let server = mock_server::MockServer::start(vec![
        mock_server::MockRoute {
            path: "/chat/completions",
            method: "POST",
            status: 401,
            body: r#"{"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}"#.to_string(),
            stream_chunks: vec![],
        },
    ]).await;

    let config = ClientConfigBuilder::new("test-key")
        .base_url(&server.url)
        .max_retries(0)
        .build();
    let client = DefaultClient::new(config, None).unwrap();

    // Build request from fixture JSON.
    let req: liter_llm::ChatCompletionRequest = serde_json::from_str(
        r#"{"messages":[{"content":"Hello","role":"user"}],"model":"vertex_ai/gemini-2.0-flash"}"#,
    )
    .unwrap();

    let result = client.chat(req).await;
    assert!(result.is_err(), "Expected error but got Ok");
    assert!(
        matches!(result.unwrap_err(), liter_llm::LiterLlmError::Authentication { .. }),
        "Expected Authentication error"
    );

    server.shutdown();
}
