<?php

declare(strict_types=1);

// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

namespace LiterLlmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class ConfigurationTest extends TestCase
{
    /** Client configured with a custom base URL routes all requests to that endpoint */
    public function testCustomBaseUrl(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-local-001","model":"local-model","object":"chat.completion","usage":{"completion_tokens":4,"prompt_tokens":3,"total_tokens":7}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"local-model"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hi there!', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(7, $doc['usage']['total_tokens']);
        $this->assertEquals('local-model', $doc['model']);
    }

    /** Client configured with extra custom headers successfully completes a chat request */
    public function testExtraHeaders(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you?","role":"assistant"}}],"created":1711000140,"id":"chatcmpl-headers001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":8,"total_tokens":16}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hello! How can I help you?', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(16, $doc['usage']['total_tokens']);
        $this->assertEquals('gpt-4', $doc['model']);
    }

    /** llamacpp local provider routes requests via llamacpp/ model prefix with no auth */
    public function testLocalProviderLlamacpp(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there! I\'m running locally.","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-llamacpp-001","model":"my-model","object":"chat.completion","usage":{"completion_tokens":6,"prompt_tokens":5,"total_tokens":11}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"llamacpp/my-model"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hi there! I\'m running locally.', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(11, $doc['usage']['total_tokens']);
        $this->assertEquals('my-model', $doc['model']);
    }

    /** Ollama local provider routes requests via ollama/ model prefix with no auth */
    public function testLocalProviderOllama(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-ollama-001","model":"qwen2:0.5b","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":5,"total_tokens":13}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"ollama/qwen2:0.5b"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hello! How can I help you today?', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(13, $doc['usage']['total_tokens']);
        $this->assertEquals('qwen2:0.5b', $doc['model']);
    }

    /** vLLM local provider routes requests via vllm/ model prefix with no auth */
    public function testLocalProviderVllm(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How may I assist you?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-vllm-001","model":"meta-llama/Llama-3.2-1B","object":"chat.completion","usage":{"completion_tokens":7,"prompt_tokens":5,"total_tokens":12}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"vllm/meta-llama/Llama-3.2-1B"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hello! How may I assist you?', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(12, $doc['usage']['total_tokens']);
        $this->assertEquals('meta-llama/Llama-3.2-1B', $doc['model']);
    }
}
