<?php

declare(strict_types=1);

// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

namespace LiterLlmE2E;

/**
 * Configuration for a single mock HTTP route.
 */
final class MockRoute
{
    public function __construct(
        public readonly string $path,
        public readonly string $method,
        public readonly int $status,
        public readonly string $body,
        /** @var list<string> */
        public readonly array $streamChunks = [],
    ) {
    }
}

/**
 * Minimal PHP built-in server-based mock HTTP server for liter-llm e2e tests.
 *
 * Writes a router script to a temp file, launches `php -S` in the background,
 * waits for it to be ready, then serves mock routes.
 */
final class MockServer
{
    public readonly string $url;
    private readonly string $routerFile;
    /** @var resource */
    private $process;

    /**
     * @param list<MockRoute> $routes
     */
    public function __construct(array $routes)
    {
        $port = $this->findFreePort();
        $this->url = "http://127.0.0.1:{$port}";

        // Encode routes as PHP data so the router script can use them.
        $routeData = json_encode(
            array_map(static fn (MockRoute $r) => [
                'path'         => $r->path,
                'method'       => strtoupper($r->method),
                'status'       => $r->status,
                'body'         => $r->body,
                'streamChunks' => $r->streamChunks,
            ], $routes),
            JSON_THROW_ON_ERROR
        );

        $this->routerFile = tempnam(sys_get_temp_dir(), 'liter_llm_mock_') . '.php';
        file_put_contents($this->routerFile, $this->buildRouterScript($routeData));

        $descriptorSpec = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $pipes = [];
        $this->process = proc_open(
            [PHP_BINARY, '-S', "127.0.0.1:{$port}", $this->routerFile],
            $descriptorSpec,
            $pipes,
            sys_get_temp_dir()
        );

        // Wait until the server is listening (up to 3 seconds).
        $deadline = microtime(true) + 3.0;
        while (microtime(true) < $deadline) {
            $sock = @fsockopen('127.0.0.1', $port, $errno, $errstr, 0.1);
            if ($sock !== false) {
                fclose($sock);
                break;
            }
            usleep(50_000);
        }
    }

    public function stop(): void
    {
        if (is_resource($this->process)) {
            proc_terminate($this->process);
            proc_close($this->process);
        }
        if (file_exists($this->routerFile)) {
            unlink($this->routerFile);
        }
    }

    private function findFreePort(): int
    {
        $sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
        socket_bind($sock, '127.0.0.1', 0);
        socket_getsockname($sock, $addr, $port);
        socket_close($sock);
        return (int) $port;
    }

    private function buildRouterScript(string $routeDataJson): string
    {
        // Base64-encode the JSON so it can be safely embedded in a PHP string
        // literal without worrying about quote or backslash escaping.
        $b64 = base64_encode($routeDataJson);
        // phpcs:disable
        return <<<PHP
        <?php
        \$routes = json_decode(base64_decode('{$b64}'), true);
        \$path   = parse_url(\$_SERVER['REQUEST_URI'], PHP_URL_PATH);
        \$method = strtoupper(\$_SERVER['REQUEST_METHOD']);

        foreach (\$routes as \$route) {
            if (\$route['path'] === \$path && \$route['method'] === \$method) {
                http_response_code(\$route['status']);
                if (!empty(\$route['streamChunks'])) {
                    header('Content-Type: text/event-stream');
                    header('Cache-Control: no-cache');
                    foreach (\$route['streamChunks'] as \$chunk) {
                        echo "data: " . \$chunk . "\n\n";
                        ob_flush();
                        flush();
                    }
                    echo "data: [DONE]\n\n";
                } else {
                    header('Content-Type: application/json');
                    echo \$route['body'];
                }
                exit;
            }
        }
        http_response_code(404);
        echo "No mock route for \$method \$path";
        PHP;
        // phpcs:enable
    }
}

/**
 * Shared HTTP helper: send a request to the mock server and return body + status.
 *
 * @return array{status: int, body: string}
 */
function httpRequest(string $url, string $method, string $body = ''): array
{
    $ctx = stream_context_create([
        'http' => [
            'method'  => strtoupper($method),
            'header'  => "Content-Type: application/json\r\n",
            'content' => $body,
            'ignore_errors' => true,
        ],
    ]);

    $responseBody = file_get_contents($url, false, $ctx);

    // Parse status from response headers.
    $status = 200;
    if (!empty($http_response_header)) {
        preg_match('/HTTP\/\S+\s+(\d+)/', $http_response_header[0], $m);
        $status = (int) ($m[1] ?? 200);
    }

    return [
        'status' => $status,
        'body'   => $responseBody !== false ? $responseBody : '',
    ];
}

/**
 * Read SSE stream from URL and return data payloads (excluding [DONE]).
 *
 * @return list<string>
 */
function readSseChunks(string $url, string $method, string $body = ''): array
{
    $ctx = stream_context_create([
        'http' => [
            'method'         => strtoupper($method),
            'header'         => "Content-Type: application/json\r\n",
            'content'        => $body,
            'ignore_errors'  => true,
        ],
    ]);

    $stream = fopen($url, 'r', false, $ctx);
    if ($stream === false) {
        return [];
    }

    $chunks = [];
    while (!feof($stream)) {
        $line = fgets($stream);
        if ($line === false) {
            break;
        }
        $line = rtrim($line);
        if (str_starts_with($line, 'data: ') && !str_contains($line, '[DONE]')) {
            $chunks[] = substr($line, 6);
        }
    }
    fclose($stream);

    return $chunks;
}
