<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;

/** E2e tests for category: moderate. */
final class ModerateTest extends TestCase
{
    /** Moderation response with multiple categories flagged */
    public function test_edge_moderate_all_categories(): void
    {
        $result = LiterLlm::chat("Extremely harmful content targeting multiple categories");
        // TODO: unsupported assertion type: count_equals
        $this->assertEquals(true, $result->results["0"]->flagged);
    }

    /** Moderation with empty string input */
    public function test_edge_moderate_empty_input(): void
    {
        $result = LiterLlm::chat("");
        // TODO: unsupported assertion type: count_equals
        $this->assertEquals(false, $result->results["0"]->flagged);
    }

    /** 401 Unauthorized for moderation with invalid API key */
    public function test_error_moderate_auth_401(): void
    {
        $this->expectException(\Exception::class);
        LiterLlm::chat("Hello");
    }

    /** 400 Bad Request for moderation with invalid model */
    public function test_error_moderate_bad_request(): void
    {
        $this->expectException(\Exception::class);
        LiterLlm::chat("Hello");
    }

    /** Moderate multiple inputs in a single request */
    public function test_smoke_moderate_batch(): void
    {
        $result = LiterLlm::chat(["Hello world", "Nice weather today"]);
        // TODO: unsupported assertion type: count_equals
        $this->assertEquals(false, $result->results["0"]->flagged);
    }

    /** Moderation detects flagged content */
    public function test_smoke_moderate_flagged(): void
    {
        $result = LiterLlm::chat("I want to hurt someone very badly");
        // TODO: unsupported assertion type: count_equals
        $this->assertEquals(true, $result->results["0"]->flagged);
    }

    /** Moderate a single non-flagged input */
    public function test_smoke_moderate_single(): void
    {
        $result = LiterLlm::chat("The weather is nice today.");
        // TODO: unsupported assertion type: count_equals
        $this->assertEquals(false, $result->results["0"]->flagged);
    }
}
