<?php

declare(strict_types=1);

// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

namespace LiterLlmE2E;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/Helpers.php';

final class ProxyTest extends TestCase
{
    /** 401 Unauthorized when an invalid API key is provided through the proxy */
    public function testProxyAuthInvalid(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 401,
                body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided: sk-invalid. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}');
        $server->stop();

        $this->assertEquals(401, $result['status']);
    }

    /** 401 Unauthorized when no API key is provided through the proxy */
    public function testProxyAuthMissing(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 401,
                body: '{"error":{"code":null,"message":"You didn\'t provide an API key. You need to provide your API key in an Authorization header.","param":null,"type":"invalid_request_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}');
        $server->stop();

        $this->assertEquals(401, $result['status']);
    }

    /** Basic chat completion request routed through the proxy */
    public function testProxyChatBasic(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-proxy001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":3,"prompt_tokens":10,"total_tokens":13}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Say hello","role":"user"}],"model":"openai/gpt-4o"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['choices']);
        $this->assertEquals('Hello!', $doc['choices'][0]['message']['content']);
        $this->assertEquals('stop', $doc['choices'][0]['finish_reason']);
        $this->assertEquals(13, $doc['usage']['total_tokens']);
        $this->assertEquals('gpt-4o', $doc['model']);
    }

    /** Streaming chat completion routed through the proxy */
    public function testProxyChatStreaming(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 200,
                body: 'null',
                streamChunks: [
                    '{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":"1"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":" 2"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":" 3"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                ],
            ),
        ];

        $server = new MockServer($routes);
        $chunks = readSseChunks($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Count to 3","role":"user"}],"model":"openai/gpt-4o","stream":true}');
        $server->stop();

        $this->assertGreaterThanOrEqual(3, count($chunks), 'Expected at least 3 chunk(s)');
    }

    /** Embedding request routed through the proxy */
    public function testProxyEmbeddings(): void
    {
        $routes = [
            new MockRoute(
                path: '/embeddings',
                method: 'POST',
                status: 200,
                body: '{"data":[{"embedding":[0.01,0.02,0.03,0.04,0.05],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/embeddings', 'POST', '{"input":"Hello world","model":"openai/text-embedding-3-small"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['data']);
    }

    /** Health check verifying proxy connectivity via list models */
    public function testProxyHealth(): void
    {
        $routes = [
            new MockRoute(
                path: '/models',
                method: 'GET',
                status: 200,
                body: '{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"}],"object":"list"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/models', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(1, $doc['data']);
    }

    /** Image generation request routed through the proxy */
    public function testProxyImageGenerate(): void
    {
        $routes = [
            new MockRoute(
                path: '/images/generations',
                method: 'POST',
                status: 200,
                body: '{"created":1711000000,"data":[{"revised_prompt":"A vivid sunset casting warm orange and pink hues over a calm ocean","url":"https://example.com/images/img-proxy001.png"}]}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/images/generations', 'POST', '{"model":"dall-e-3","n":1,"prompt":"A sunset over the ocean","size":"1024x1024"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** List models request routed through the proxy */
    public function testProxyModelsList(): void
    {
        $routes = [
            new MockRoute(
                path: '/models',
                method: 'GET',
                status: 200,
                body: '{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"},{"created":1721172741,"id":"gpt-4o-mini","object":"model","owned_by":"openai"}],"object":"list"}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/models', 'GET');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

        $this->assertCount(2, $doc['data']);
    }

    /** Content moderation request routed through the proxy */
    public function testProxyModeration(): void
    {
        $routes = [
            new MockRoute(
                path: '/moderations',
                method: 'POST',
                status: 200,
                body: '{"id":"modr-proxy001","model":"omni-moderation-latest","results":[{"categories":{"harassment":false,"harassment/threatening":false,"hate":false,"hate/threatening":false,"self-harm":false,"self-harm/instructions":false,"self-harm/intent":false,"sexual":false,"sexual/minors":false,"violence":false,"violence/graphic":false},"category_scores":{"harassment":0.0002,"harassment/threatening":0.0001,"hate":0.0001,"hate/threatening":0.0001,"self-harm":0.0001,"self-harm/instructions":0.0001,"self-harm/intent":0.0001,"sexual":0.0001,"sexual/minors":0.0001,"violence":0.0001,"violence/graphic":0.0001},"flagged":false}]}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/moderations', 'POST', '{"input":"The weather is nice today.","model":"omni-moderation-latest"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** Document reranking request routed through the proxy */
    public function testProxyRerank(): void
    {
        $routes = [
            new MockRoute(
                path: '/rerank',
                method: 'POST',
                status: 200,
                body: '{"id":"rerank-proxy001","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.95},{"index":1,"relevance_score":0.03}]}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/rerank', 'POST', '{"documents":["Deep learning is a subset of machine learning using neural networks.","The stock market closed higher today."],"model":"rerank-v3.5","query":"What is deep learning?"}');
        $server->stop();

        $this->assertEquals(200, $result['status']);
        $doc = json_decode($result['body'], true, 512, JSON_THROW_ON_ERROR);

    }

    /** 429 Too Many Requests from upstream provider through the proxy */
    public function testProxyUpstream429(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 429,
                body: '{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4o in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}');
        $server->stop();

        $this->assertEquals(429, $result['status']);
    }

    /** 500 Internal Server Error from upstream provider through the proxy */
    public function testProxyUpstream500(): void
    {
        $routes = [
            new MockRoute(
                path: '/chat/completions',
                method: 'POST',
                status: 500,
                body: '{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}',
                streamChunks: [],
            ),
        ];

        $server = new MockServer($routes);
        $result = httpRequest($server->url . '/chat/completions', 'POST', '{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}');
        $server->stop();

        $this->assertEquals(500, $result['status']);
    }
}
