// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "@kreuzberg/liter-llm";

describe("configuration", () => {
  // Client configured with a custom base URL routes all requests to that endpoint
  it("custom_base_url", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: `{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-local-001","model":"local-model","object":"chat.completion","usage":{"completion_tokens":4,"prompt_tokens":3,"total_tokens":7}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const response = await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"local-model"}`));

      expect(response.choices.length, "Choices count mismatch").toBe(1);
      expect(response.choices[0].finishReason, "finish_reason mismatch").toBe("stop");
      expect(response.choices[0].message.content, "message content mismatch").toBe("Hi there!");
      expect(response.usage, "Expected usage object").toBeTruthy();
      expect(response.usage.totalTokens, "total_tokens mismatch").toBe(7);
      expect(response.model, "model mismatch").toBe("local-model");
    } finally {
      server.close();
    }
  });

  // Client configured with extra custom headers successfully completes a chat request
  it("extra_headers", async () => {
    const routes: MockRoute[] = [
      {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: `{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you?","role":"assistant"}}],"created":1711000140,"id":"chatcmpl-headers001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":8,"total_tokens":16}}`,
        streamChunks: [],
      },
    ];

    const server = await startMockServer(routes);
    try {
      const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

      const response = await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}`));

      expect(response.choices.length, "Choices count mismatch").toBe(1);
      expect(response.choices[0].finishReason, "finish_reason mismatch").toBe("stop");
      expect(response.choices[0].message.content, "message content mismatch").toBe("Hello! How can I help you?");
      expect(response.usage, "Expected usage object").toBeTruthy();
      expect(response.usage.totalTokens, "total_tokens mismatch").toBe(16);
      expect(response.model, "model mismatch").toBe("gpt-4");
    } finally {
      server.close();
    }
  });

});
