// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "@kreuzberg/liter-llm";

describe("files", () => {
	// List files when no files have been uploaded
	it("edge_file_empty_list", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files",
				method: "GET",
				status: 200,
				body: `{"data":[],"object":"list"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "list_files"
		} finally {
			server.close();
		}
	});

	// Upload a large file successfully
	it("edge_file_large_upload", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files",
				method: "POST",
				status: 200,
				body: `{"bytes":536870912,"created_at":1711000000,"filename":"large_training_data.jsonl","id":"file-large001","object":"file","purpose":"fine-tune","status":"processed"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "create_file"
		} finally {
			server.close();
		}
	});

	// 401 Unauthorized when listing files with invalid API key
	it("error_file_auth_401", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files",
				method: "GET",
				status: 401,
				body: `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "list_files"
		} finally {
			server.close();
		}
	});

	// 400 Bad Request when uploading a file with invalid purpose
	it("error_file_bad_purpose", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files",
				method: "POST",
				status: 400,
				body: `{"error":{"code":null,"message":"Invalid value for 'purpose': 'invalid-purpose'. Supported values are: 'fine-tune', 'assistants', 'batch'.","param":"purpose","type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "create_file"
		} finally {
			server.close();
		}
	});

	// 404 Not Found when retrieving a nonexistent file
	it("error_file_not_found", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files/file-placeholder",
				method: "GET",
				status: 404,
				body: `{"error":{"code":null,"message":"No such File object: file-nonexistent","param":null,"type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "retrieve_file"
		} finally {
			server.close();
		}
	});

	// Upload a file for use with the API
	it("smoke_create_file", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files",
				method: "POST",
				status: 200,
				body: `{"bytes":1024,"created_at":1711000000,"filename":"training_data.jsonl","id":"file-abc123","object":"file","purpose":"fine-tune","status":"processed"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "create_file"
		} finally {
			server.close();
		}
	});

	// Delete an uploaded file
	it("smoke_delete_file", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files/file-placeholder",
				method: "POST",
				status: 200,
				body: `{"deleted":true,"id":"file-abc123","object":"file"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "delete_file"
		} finally {
			server.close();
		}
	});

	// Retrieve the content of an uploaded file
	it("smoke_file_content", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files/file-placeholder/content",
				method: "GET",
				status: 200,
				body: `{"_binary":true,"_content_type":"application/octet-stream","_description":"Mock file content bytes"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "file_content"
		} finally {
			server.close();
		}
	});

	// List all uploaded files
	it("smoke_list_files", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files",
				method: "GET",
				status: 200,
				body: `{"data":[{"bytes":1024,"created_at":1711000000,"filename":"training_data.jsonl","id":"file-abc123","object":"file","purpose":"fine-tune","status":"processed"},{"bytes":2048,"created_at":1711000100,"filename":"batch_input.jsonl","id":"file-def456","object":"file","purpose":"batch","status":"processed"}],"object":"list"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "list_files"
		} finally {
			server.close();
		}
	});

	// Retrieve metadata for an uploaded file
	it("smoke_retrieve_file", async () => {
		const routes: MockRoute[] = [
			{
				path: "/files/file-placeholder",
				method: "GET",
				status: 200,
				body: `{"bytes":1024,"created_at":1711000000,"filename":"training_data.jsonl","id":"file-abc123","object":"file","purpose":"fine-tune","status":"processed"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "retrieve_file"
		} finally {
			server.close();
		}
	});
});
