// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "@kreuzberg/liter-llm";

describe("image-generate", () => {
	// Image generation returning base64-encoded data instead of URL
	it("edge_image_b64_response", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 200,
				body: `{"created":1711000000,"data":[{"b64_json":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==","revised_prompt":"A perfect blue circle on a white background"}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// Image generation with an empty prompt returns 400
	it("edge_image_empty_prompt", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 400,
				body: `{"error":{"code":null,"message":"You must provide a prompt.","param":"prompt","type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// 401 Unauthorized when generating images with invalid API key
	it("error_image_auth_401", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 401,
				body: `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// 400 Bad Request when image generation parameters are invalid
	it("error_image_bad_request", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 400,
				body: `{"error":{"code":null,"message":"Invalid value for 'size': '9999x9999'. Supported values are: '1024x1024', '1792x1024', '1024x1792'.","param":"size","type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// 429 Rate limit exceeded for image generation
	it("error_image_rate_limit", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 429,
				body: `{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for images per minute. Limit: 5, Used: 5, Requested: 1.","param":null,"type":"rate_limit_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// Basic image generation with a text prompt
	it("smoke_image_basic", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 200,
				body: `{"created":1711000000,"data":[{"revised_prompt":"A fluffy white cat sitting peacefully on a sunlit windowsill","url":"https://example.com/images/img-abc123.png"}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// Image generation requesting multiple images
	it("smoke_image_multiple", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 200,
				body: `{"created":1711000000,"data":[{"url":"https://example.com/images/img-001.png"},{"url":"https://example.com/images/img-002.png"},{"url":"https://example.com/images/img-003.png"}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// Image generation with explicit size parameter
	it("smoke_image_with_size", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 200,
				body: `{"created":1711000000,"data":[{"revised_prompt":"A breathtaking sunset over snow-capped mountains","url":"https://example.com/images/img-def456.png"}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});
});
