// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "@kreuzberg/liter-llm";

describe("proxy", () => {
	// 401 Unauthorized when an invalid API key is provided through the proxy
	it("proxy_auth_invalid", async () => {
		const routes: MockRoute[] = [
			{
				path: "/chat/completions",
				method: "POST",
				status: 401,
				body: `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided: sk-invalid. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			let threw = false;
			try {
				await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}`));
			} catch (e) {
				threw = true;
				expect((e as Error).message ?? "", "Expected [Authentication] error").toMatch(
					/\[Authentication\]|Authentication/i,
				);
			}
			expect(threw, "Expected client.chat to throw").toBe(true);
		} finally {
			server.close();
		}
	});

	// 401 Unauthorized when no API key is provided through the proxy
	it("proxy_auth_missing", async () => {
		const routes: MockRoute[] = [
			{
				path: "/chat/completions",
				method: "POST",
				status: 401,
				body: `{"error":{"code":null,"message":"You didn't provide an API key. You need to provide your API key in an Authorization header.","param":null,"type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			let threw = false;
			try {
				await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}`));
			} catch (e) {
				threw = true;
				expect((e as Error).message ?? "", "Expected [Authentication] error").toMatch(
					/\[Authentication\]|Authentication/i,
				);
			}
			expect(threw, "Expected client.chat to throw").toBe(true);
		} finally {
			server.close();
		}
	});

	// Basic chat completion request routed through the proxy
	it("proxy_chat_basic", async () => {
		const routes: MockRoute[] = [
			{
				path: "/chat/completions",
				method: "POST",
				status: 200,
				body: `{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-proxy001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":3,"prompt_tokens":10,"total_tokens":13}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			const response = await client.chat(
				JSON.parse(`{"messages":[{"content":"Say hello","role":"user"}],"model":"openai/gpt-4o"}`),
			);

			expect(response.choices.length, "Choices count mismatch").toBe(1);
			expect(response.choices[0].finishReason, "finish_reason mismatch").toBe("stop");
			expect(response.choices[0].message.content, "message content mismatch").toBe("Hello!");
			expect(response.usage, "Expected usage object").toBeTruthy();
			expect(response.usage.totalTokens, "total_tokens mismatch").toBe(13);
			expect(response.model, "model mismatch").toBe("gpt-4o");
		} finally {
			server.close();
		}
	});

	// Streaming chat completion routed through the proxy
	it("proxy_chat_streaming", async () => {
		const routes: MockRoute[] = [
			{
				path: "/chat/completions",
				method: "POST",
				status: 200,
				body: `null`,
				streamChunks: [
					`{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}`,
					`{"choices":[{"delta":{"content":"1"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}`,
					`{"choices":[{"delta":{"content":" 2"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}`,
					`{"choices":[{"delta":{"content":" 3"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}`,
					`{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}`,
				],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			const stream = await client.chatStream(
				JSON.parse(`{"messages":[{"content":"Count to 3","role":"user"}],"model":"openai/gpt-4o","stream":true}`),
			);
			const chunks: unknown[] = [];
			for await (const chunk of stream) {
				chunks.push(chunk);
			}

			expect(chunks.length, "Expected at least 3 chunk(s)").toBeGreaterThanOrEqual(3);
			const content = chunks
				.flatMap((c: unknown) => (c as { choices?: { delta?: { content?: string } }[] }).choices ?? [])
				.map((ch: { delta?: { content?: string } }) => ch.delta?.content ?? "")
				.join("");
			expect(content, "Stream content mismatch").toBe("1 2 3");
		} finally {
			server.close();
		}
	});

	// Embedding request routed through the proxy
	it("proxy_embeddings", async () => {
		const routes: MockRoute[] = [
			{
				path: "/embeddings",
				method: "POST",
				status: 200,
				body: `{"data":[{"embedding":[0.01,0.02,0.03,0.04,0.05],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			const response = await client.embed(
				JSON.parse(`{"input":"Hello world","model":"openai/text-embedding-3-small"}`),
			);

			expect(response.data.length, "Expected at least 1 embedding(s)").toBeGreaterThanOrEqual(1);
			expect(response.data.length, "Embedding count mismatch").toBe(1);
			expect(response.data[0].embedding.length, "Embedding dimension mismatch").toBe(5);
		} finally {
			server.close();
		}
	});

	// Health check verifying proxy connectivity via list models
	it("proxy_health", async () => {
		const routes: MockRoute[] = [
			{
				path: "/models",
				method: "GET",
				status: 200,
				body: `{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"}],"object":"list"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			const response = await client.listModels();

			expect(response.data.length, "Expected at least 1 model(s)").toBeGreaterThanOrEqual(1);
			expect(response.data.length, "Model count mismatch").toBe(1);
		} finally {
			server.close();
		}
	});

	// Image generation request routed through the proxy
	it("proxy_image_generate", async () => {
		const routes: MockRoute[] = [
			{
				path: "/images/generations",
				method: "POST",
				status: 200,
				body: `{"created":1711000000,"data":[{"revised_prompt":"A vivid sunset casting warm orange and pink hues over a calm ocean","url":"https://example.com/images/img-proxy001.png"}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "image_generate"
		} finally {
			server.close();
		}
	});

	// List models request routed through the proxy
	it("proxy_models_list", async () => {
		const routes: MockRoute[] = [
			{
				path: "/models",
				method: "GET",
				status: 200,
				body: `{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"},{"created":1721172741,"id":"gpt-4o-mini","object":"model","owned_by":"openai"}],"object":"list"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			const response = await client.listModels();

			expect(response.data.length, "Expected at least 1 model(s)").toBeGreaterThanOrEqual(1);
			expect(response.data.length, "Model count mismatch").toBe(2);
		} finally {
			server.close();
		}
	});

	// Content moderation request routed through the proxy
	it("proxy_moderation", async () => {
		const routes: MockRoute[] = [
			{
				path: "/moderations",
				method: "POST",
				status: 200,
				body: `{"id":"modr-proxy001","model":"omni-moderation-latest","results":[{"categories":{"harassment":false,"harassment/threatening":false,"hate":false,"hate/threatening":false,"self-harm":false,"self-harm/instructions":false,"self-harm/intent":false,"sexual":false,"sexual/minors":false,"violence":false,"violence/graphic":false},"category_scores":{"harassment":0.0002,"harassment/threatening":0.0001,"hate":0.0001,"hate/threatening":0.0001,"self-harm":0.0001,"self-harm/instructions":0.0001,"self-harm/intent":0.0001,"sexual":0.0001,"sexual/minors":0.0001,"violence":0.0001,"violence/graphic":0.0001},"flagged":false}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "moderate"
		} finally {
			server.close();
		}
	});

	// Document reranking request routed through the proxy
	it("proxy_rerank", async () => {
		const routes: MockRoute[] = [
			{
				path: "/rerank",
				method: "POST",
				status: 200,
				body: `{"id":"rerank-proxy001","meta":{"api_version":{"version":"2"},"billed_units":{"search_units":1}},"results":[{"index":0,"relevance_score":0.95},{"index":1,"relevance_score":0.03}]}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "rerank"
		} finally {
			server.close();
		}
	});

	// 429 Too Many Requests from upstream provider through the proxy
	it("proxy_upstream_429", async () => {
		const routes: MockRoute[] = [
			{
				path: "/chat/completions",
				method: "POST",
				status: 429,
				body: `{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4o in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			let threw = false;
			try {
				await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}`));
			} catch (e) {
				threw = true;
				expect((e as Error).message ?? "", "Expected [RateLimited] error").toMatch(/\[RateLimited\]|RateLimited/i);
			}
			expect(threw, "Expected client.chat to throw").toBe(true);
		} finally {
			server.close();
		}
	});

	// 500 Internal Server Error from upstream provider through the proxy
	it("proxy_upstream_500", async () => {
		const routes: MockRoute[] = [
			{
				path: "/chat/completions",
				method: "POST",
				status: 500,
				body: `{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			let threw = false;
			try {
				await client.chat(JSON.parse(`{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}`));
			} catch (e) {
				threw = true;
				expect((e as Error).message ?? "", "Expected [ServerError] error").toMatch(/\[ServerError\]|ServerError/i);
			}
			expect(threw, "Expected client.chat to throw").toBe(true);
		} finally {
			server.close();
		}
	});
});
