// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { startMockServer, type MockServer, type MockRoute } from "./helpers";
// @ts-ignore – binding not yet implemented; tests compile and fail at runtime
import { LlmClient } from "@kreuzberg/liter-llm";

describe("speech", () => {
	// Speech generation with a very long input text
	it("edge_speech_long_input", async () => {
		const routes: MockRoute[] = [
			{
				path: "/audio/speech",
				method: "POST",
				status: 200,
				body: `{"_binary":true,"_content_type":"audio/mpeg","_description":"Mock binary audio data for long text"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "speech"
		} finally {
			server.close();
		}
	});

	// 401 Unauthorized for speech generation with invalid API key
	it("error_speech_auth_401", async () => {
		const routes: MockRoute[] = [
			{
				path: "/audio/speech",
				method: "POST",
				status: 401,
				body: `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "speech"
		} finally {
			server.close();
		}
	});

	// 400 Bad Request for speech with unsupported model
	it("error_speech_bad_model", async () => {
		const routes: MockRoute[] = [
			{
				path: "/audio/speech",
				method: "POST",
				status: 400,
				body: `{"error":{"code":"model_not_found","message":"The model 'tts-nonexistent' does not exist.","param":"model","type":"invalid_request_error"}}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "speech"
		} finally {
			server.close();
		}
	});

	// Basic text-to-speech generation
	it("smoke_speech_basic", async () => {
		const routes: MockRoute[] = [
			{
				path: "/audio/speech",
				method: "POST",
				status: 200,
				body: `{"_binary":true,"_content_type":"audio/mpeg","_description":"Mock binary audio data"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "speech"
		} finally {
			server.close();
		}
	});

	// Text-to-speech with explicit MP3 response format
	it("smoke_speech_mp3_format", async () => {
		const routes: MockRoute[] = [
			{
				path: "/audio/speech",
				method: "POST",
				status: 200,
				body: `{"_binary":true,"_content_type":"audio/mpeg","_description":"Mock MP3 audio data"}`,
				streamChunks: [],
			},
		];

		const server = await startMockServer(routes);
		try {
			const client = new LlmClient({ apiKey: "test-key", baseUrl: server.url });

			// TODO: unknown method "speech"
		} finally {
			server.close();
		}
	});
});
