// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literllm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: budget. */
class BudgetTest {

  /** Tests that a request is rejected when budget is exceeded */
  @Test
  void budgetEnforced() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(new Helpers.MockRoute("/chat/completions", "POST", 200, "{}")))) {
      String mockUrl = server.url;

      // TDD: Budget tests — will fail until budget feature is implemented.
      // Budget config: "{\"enforcement\":\"hard\",\"global_limit\":0.0}"
      var config =
          new LlmClientConfig.Builder()
              .apiKey("test-key")
              .baseUrl(mockUrl)
              .budget(new BudgetConfig(0.001, "hard"))
              .build();
      var client = new LlmClient(config);

      var request =
          "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}";
      assertThrows(
          BudgetExceededException.class,
          () -> client.chat(request),
          "Expected BudgetExceededException when budget is exceeded");
    }
  }

  /** Tests per-model budget limit */
  @Test
  void budgetPerModel() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(new Helpers.MockRoute("/chat/completions", "POST", 200, "{}")))) {
      String mockUrl = server.url;

      // TDD: Budget tests — will fail until budget feature is implemented.
      // Budget config: "{\"enforcement\":\"hard\",\"model_limits\":{\"gpt-4\":0.0}}"
      var config =
          new LlmClientConfig.Builder()
              .apiKey("test-key")
              .baseUrl(mockUrl)
              .budget(new BudgetConfig(0.001, "hard"))
              .build();
      var client = new LlmClient(config);

      var request =
          "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}";
      assertThrows(
          BudgetExceededException.class,
          () -> client.chat(request),
          "Expected BudgetExceededException when budget is exceeded");
    }
  }

  /** Tests that cost is tracked after a successful response */
  @Test
  void budgetTracked() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello!"
                        + " How can I help you"
                        + " today?\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-budget-tracked-001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":9,\"prompt_tokens\":8,\"total_tokens\":17}}")))) {
      String mockUrl = server.url;

      // TDD: Budget tests — will fail until budget feature is implemented.
      var config =
          new LlmClientConfig.Builder()
              .apiKey("test-key")
              .baseUrl(mockUrl)
              .budget(new BudgetConfig(10.0, "soft"))
              .build();
      var client = new LlmClient(config);

      var request =
          "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}";
      var resp = client.chat(request);
      assertNotNull(resp, "Expected successful response");
      assertTrue(client.getBudgetUsage() > 0, "Expected cost to be tracked");
    }
  }
}
