// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literllm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import java.net.http.HttpResponse;
import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: chat. */
class ChatTest {

  /** Chat request that includes a developer role message alongside user messages */
  @Test
  void developerMessage() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"s[::-1]\",\"role\":\"assistant\"}}],\"created\":1711000130,\"id\":\"chatcmpl-dev001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":28,\"total_tokens\":33}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"You are a coding assistant. Always respond with"
                  + " concise code examples.\",\"role\":\"developer\"},{\"content\":\"How do I"
                  + " reverse a string in Python?\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "s[::-1]", body.at("/choices/0/message/content").asText(), "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(33, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /**
   * Chat response stopped by content filter with finish_reason of content_filter and null content
   */
  @Test
  void finishReasonContentFilter() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"content_filter\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\"}}],\"created\":1711000100,\"id\":\"chatcmpl-filter001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":14,\"total_tokens\":14}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Tell me something"
                  + " controversial\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals("content_filter", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(14, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat response truncated due to max_tokens limit with finish_reason of length */
  @Test
  void finishReasonLength() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"length\",\"index\":0,\"message\":{\"content\":\"Once"
                        + " upon a"
                        + " time\",\"role\":\"assistant\"}}],\"created\":1711000090,\"id\":\"chatcmpl-length001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":5,\"prompt_tokens\":12,\"total_tokens\":17}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"max_tokens\":5,\"messages\":[{\"content\":\"Tell me a long"
                  + " story\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "Once upon a time",
          body.at("/choices/0/message/content").asText(),
          "first choice content");
      assertEquals("length", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(17, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Multi-turn conversation with system, user, assistant, and follow-up user messages */
  @Test
  void multiTurnConversation() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"4"
                        + " + 4 equals"
                        + " 8.\",\"role\":\"assistant\"}}],\"created\":1711000030,\"id\":\"chatcmpl-multi001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":9,\"prompt_tokens\":45,\"total_tokens\":54}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"You are a helpful"
                  + " assistant.\",\"role\":\"system\"},{\"content\":\"What is 2 +"
                  + " 2?\",\"role\":\"user\"},{\"content\":\"2 + 2 equals"
                  + " 4.\",\"role\":\"assistant\"},{\"content\":\"And what is 4 +"
                  + " 4?\",\"role\":\"user\"}],\"model\":\"gpt-4\"}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "4 + 4 equals 8.",
          body.at("/choices/0/message/content").asText(),
          "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(54, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat request that results in parallel tool calls in the response */
  @Test
  void parallelToolCalls() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\":"
                        + " \\\"New"
                        + " York\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_par001\",\"type\":\"function\"},{\"function\":{\"arguments\":\"{\\\"location\\\":"
                        + " \\\"London\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_par002\",\"type\":\"function\"}]}}],\"created\":1711000060,\"id\":\"chatcmpl-parallel001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":30,\"prompt_tokens\":65,\"total_tokens\":95}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"What is the weather in NYC and"
                  + " London?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"parallel_tool_calls\":true,\"tools\":[{\"function\":{\"description\":\"Get"
                  + " the current weather for a given"
                  + " location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The"
                  + " city"
                  + " name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals("tool_calls", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(95, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat request with response_format json_object that returns valid JSON content */
  @Test
  void responseFormatJsonObject() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"{\\\"name\\\":"
                        + " \\\"Alice\\\", \\\"age\\\":"
                        + " 30}\",\"role\":\"assistant\"}}],\"created\":1711000070,\"id\":\"chatcmpl-json001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":12,\"prompt_tokens\":25,\"total_tokens\":37}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Respond with JSON"
                  + " only.\",\"role\":\"system\"},{\"content\":\"Give me a user object with name"
                  + " and age"
                  + " fields.\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"response_format\":{\"type\":\"json_object\"}}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "{\"name\": \"Alice\", \"age\": 30}",
          body.at("/choices/0/message/content").asText(),
          "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(37, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat request with response_format json_schema that validates the output structure */
  @Test
  void responseFormatJsonSchema() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"{\\\"temp\\\":"
                        + " 18.5}\",\"role\":\"assistant\"}}],\"created\":1711000080,\"id\":\"chatcmpl-schema001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":8,\"prompt_tokens\":30,\"total_tokens\":38}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"What is the temperature in Paris"
                  + " today?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"response_format\":{\"json_schema\":{\"name\":\"weather\",\"schema\":{\"properties\":{\"temp\":{\"type\":\"number\"}},\"required\":[\"temp\"],\"type\":\"object\"}},\"type\":\"json_schema\"}}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "{\"temp\": 18.5}",
          body.at("/choices/0/message/content").asText(),
          "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(38, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /**
   * Chat request with seed parameter for deterministic output; response includes system_fingerprint
   */
  @Test
  void seedParameter() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"7\",\"role\":\"assistant\"}}],\"created\":1711000120,\"id\":\"chatcmpl-seed001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"system_fingerprint\":\"fp_abc12345\",\"usage\":{\"completion_tokens\":1,\"prompt_tokens\":12,\"total_tokens\":13}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Pick a random"
                  + " number\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"seed\":42}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals("7", body.at("/choices/0/message/content").asText(), "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(13, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat request with custom stop sequences that terminates generation at a stop token */
  @Test
  void stopSequences() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Item"
                        + " 1\\n"
                        + "Item 2\\n"
                        + "\",\"role\":\"assistant\"}}],\"created\":1711000110,\"id\":\"chatcmpl-stop001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":7,\"prompt_tokens\":18,\"total_tokens\":25}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"List items until you see"
                  + " STOP\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stop\":[\"STOP\",\"END\"]}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals(
          "Item 1\nItem 2\n",
          body.at("/choices/0/message/content").asText(),
          "first choice content");
      assertEquals("stop", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(25, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat request with tool_choice set to required forces the model to call a tool */
  @Test
  void toolChoiceRequired() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\":"
                        + " \\\"New"
                        + " York\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_req001\",\"type\":\"function\"}]}}],\"created\":1711000040,\"id\":\"chatcmpl-required001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":15,\"prompt_tokens\":60,\"total_tokens\":75}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"What is the weather"
                  + " today?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":\"required\",\"tools\":[{\"function\":{\"description\":\"Get"
                  + " the current weather for a given"
                  + " location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The"
                  + " city"
                  + " name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals("tool_calls", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(75, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }

  /** Chat request with tool_choice specifying a particular function to call */
  @Test
  void toolChoiceSpecific() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "{\"choices\":[{\"finish_reason\":\"tool_calls\",\"index\":0,\"message\":{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\":"
                        + " \\\"Paris\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_spec001\",\"type\":\"function\"}]}}],\"created\":1711000050,\"id\":\"chatcmpl-specific001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":12,\"prompt_tokens\":75,\"total_tokens\":87}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"What is the weather in"
                  + " Paris?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"tool_choice\":{\"function\":{\"name\":\"get_weather\"},\"type\":\"function\"},\"tools\":[{\"function\":{\"description\":\"Get"
                  + " the current weather for a given"
                  + " location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The"
                  + " city"
                  + " name\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"},{\"function\":{\"description\":\"Search"
                  + " the web for"
                  + " information\",\"name\":\"search_web\",\"parameters\":{\"properties\":{\"query\":{\"description\":\"The"
                  + " search"
                  + " query\",\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}},\"type\":\"function\"}]}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      JsonNode body = Helpers.MAPPER.readTree(resp.body());

      assertEquals(1, body.get("choices").size(), "choices count");
      assertEquals("tool_calls", body.at("/choices/0/finish_reason").asText(), "finish_reason");
      assertEquals("gpt-4", body.get("model").asText(), "model");
      assertNotNull(body.get("usage"), "usage object");
      assertEquals(87, body.at("/usage/total_tokens").asLong(), "total_tokens");
    }
  }
}
