// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
package dev.kreuzberg.literllm.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import java.net.http.HttpResponse;
import java.util.List;
import org.junit.jupiter.api.Test;

/** E2E tests for category: streaming. */
class StreamingTest {

  /**
   * Streaming chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) yielding
   * multiple SSE chunks
   */
  @Test
  void anthropicStream() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000200,\"id\":\"chatcmpl-anthropic-stream001\",\"model\":\"claude-3-5-sonnet-20241022\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"One\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000200,\"id\":\"chatcmpl-anthropic-stream001\",\"model\":\"claude-3-5-sonnet-20241022\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " Two\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000200,\"id\":\"chatcmpl-anthropic-stream001\",\"model\":\"claude-3-5-sonnet-20241022\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " Three\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000200,\"id\":\"chatcmpl-anthropic-stream001\",\"model\":\"claude-3-5-sonnet-20241022\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000200,\"id\":\"chatcmpl-anthropic-stream001\",\"model\":\"claude-3-5-sonnet-20241022\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"max_tokens\":32,\"messages\":[{\"content\":\"Count to three, one word per"
                  + " response.\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 3, "expected at least 3 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("One Two Three", content.toString(), "stream content");
    }
  }

  /**
   * Streaming chat completion via Azure OpenAI — verifies the azure/ prefix routes correctly and
   * SSE chunks are delivered in the standard OpenAI chat.completion.chunk shape
   */
  @Test
  void azureStream() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-azure-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"1\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-azure-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " 2\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-azure-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " 3\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-azure-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-azure-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Count to"
                  + " 3\",\"role\":\"user\"}],\"model\":\"azure/gpt-4\",\"stream\":true,\"temperature\":0}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 3, "expected at least 3 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("1 2 3", content.toString(), "stream content");
    }
  }

  /** Streaming chat completion that produces content across multiple SSE chunks */
  @Test
  void basicStream() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"1\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " 2\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " 3\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-stream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Count to"
                  + " 3\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 3, "expected at least 3 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("1 2 3", content.toString(), "stream content");
    }
  }

  /**
   * Streaming chat completion via the AWS Bedrock provider using the bedrock/ prefix — verifies SSE
   * chunks are yielded and assembled correctly from the Converse streaming API
   */
  @Test
  void bedrockStream() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-bedrock-stream001\",\"model\":\"anthropic.claude-3-sonnet-20240229-v1:0\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"One\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-bedrock-stream001\",\"model\":\"anthropic.claude-3-sonnet-20240229-v1:0\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " Two\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-bedrock-stream001\",\"model\":\"anthropic.claude-3-sonnet-20240229-v1:0\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " Three\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-bedrock-stream001\",\"model\":\"anthropic.claude-3-sonnet-20240229-v1:0\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000300,\"id\":\"chatcmpl-bedrock-stream001\",\"model\":\"anthropic.claude-3-sonnet-20240229-v1:0\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"max_tokens\":32,\"messages\":[{\"content\":\"Count to three, one word per"
                  + " response.\",\"role\":\"user\"}],\"model\":\"bedrock/anthropic.claude-3-sonnet-20240229-v1:0\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 3, "expected at least 3 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("One Two Three", content.toString(), "stream content");
    }
  }

  /** Streaming chat completion that produces no content chunks before the DONE signal */
  @Test
  void emptyStream() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(new Helpers.MockRoute("/chat/completions", "POST", 200, "null")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Say"
                  + " nothing\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.isEmpty(), "expected 0 chunks for empty stream");
    }
  }

  /** Streaming chat completion via Ollama local provider with SSE chunks */
  @Test
  void localStreamOllama() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-ollama-s1\",\"model\":\"qwen2:0.5b\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"1"
                            + " \"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-ollama-s1\",\"model\":\"qwen2:0.5b\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"2"
                            + " \"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-ollama-s1\",\"model\":\"qwen2:0.5b\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"3\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-ollama-s1\",\"model\":\"qwen2:0.5b\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000000,\"id\":\"chatcmpl-ollama-s1\",\"model\":\"qwen2:0.5b\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Count to"
                  + " 3\",\"role\":\"user\"}],\"model\":\"ollama/qwen2:0.5b\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 3, "expected at least 3 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("1 2 3", content.toString(), "stream content");
    }
  }

  /** Verify that the [DONE] sentinel signal properly terminates the stream */
  @Test
  void streamDoneSignal() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"Done\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000001,\"id\":\"chatcmpl-done001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Say"
                  + " done\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 1, "expected at least 1 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("Done", content.toString(), "stream content");
    }
  }

  /** 401 Unauthorized error on stream initiation before any chunks are received */
  @Test
  void streamError401() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    401,
                    "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key"
                        + " provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}")))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}");

      assertEquals(401, resp.statusCode(), "HTTP status code");
      assertTrue(resp.statusCode() >= 400, "expected error status");
    }
  }

  /**
   * Streaming chat completion where the assistant responds with a tool call across multiple chunks
   */
  @Test
  void streamWithToolCalls() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"name\":\"get_weather\"},\"id\":\"call_1\",\"index\":0,\"type\":\"function\"}]},\"finish_reason\":null,\"index\":0}],\"created\":1711000010,\"id\":\"chatcmpl-toolstream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"loc\"},\"index\":0}]},\"finish_reason\":null,\"index\":0}],\"created\":1711000010,\"id\":\"chatcmpl-toolstream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"tool_calls\":[{\"function\":{\"arguments\":\"ation\\\":\\\"NYC\\\"}\"},\"index\":0}]},\"finish_reason\":null,\"index\":0}],\"created\":1711000010,\"id\":\"chatcmpl-toolstream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"tool_calls\",\"index\":0}],\"created\":1711000010,\"id\":\"chatcmpl-toolstream001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"What is the weather in"
                  + " NYC?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true,\"tools\":[{\"function\":{\"description\":\"Get"
                  + " the current weather for a given"
                  + " location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{\"location\":{\"description\":\"The"
                  + " city and state, e.g. New York,"
                  + " NY\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":\"object\"}},\"type\":\"function\"}]}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 1, "expected at least 1 chunk(s)");
    }
  }

  /** Streaming chat completion that includes a usage summary in the final chunk */
  @Test
  void streamWithUsage() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000020,\"id\":\"chatcmpl-usage001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"Hi\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000020,\"id\":\"chatcmpl-usage001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " there!\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000020,\"id\":\"chatcmpl-usage001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000020,\"id\":\"chatcmpl-usage001\",\"model\":\"gpt-4\",\"object\":\"chat.completion.chunk\",\"usage\":{\"completion_tokens\":8,\"prompt_tokens\":10,\"total_tokens\":18}}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"messages\":[{\"content\":\"Say"
                  + " hi\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true,\"stream_options\":{\"include_usage\":true}}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 2, "expected at least 2 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("Hi there!", content.toString(), "stream content");
    }
  }

  /**
   * Streaming chat completion via the Google Vertex AI provider using the vertex_ai/ prefix —
   * verifies SSE chunks from the Gemini streaming endpoint are yielded and assembled correctly
   */
  @Test
  void vertexStream() throws Exception {
    try (Helpers.MockServer server =
        new Helpers.MockServer(
            List.of(
                new Helpers.MockRoute(
                    "/chat/completions",
                    "POST",
                    200,
                    "null",
                    List.of(
                        "{\"choices\":[{\"delta\":{\"content\":\"\",\"role\":\"assistant\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000400,\"id\":\"chatcmpl-vertex-stream001\",\"model\":\"gemini-2.0-flash\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\"One\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000400,\"id\":\"chatcmpl-vertex-stream001\",\"model\":\"gemini-2.0-flash\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " Two\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000400,\"id\":\"chatcmpl-vertex-stream001\",\"model\":\"gemini-2.0-flash\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{\"content\":\""
                            + " Three\"},\"finish_reason\":null,\"index\":0}],\"created\":1711000400,\"id\":\"chatcmpl-vertex-stream001\",\"model\":\"gemini-2.0-flash\",\"object\":\"chat.completion.chunk\"}",
                        "{\"choices\":[{\"delta\":{},\"finish_reason\":\"stop\",\"index\":0}],\"created\":1711000400,\"id\":\"chatcmpl-vertex-stream001\",\"model\":\"gemini-2.0-flash\",\"object\":\"chat.completion.chunk\"}"))))) {

      HttpResponse<String> resp =
          Helpers.postJson(
              server.url,
              "/chat/completions",
              "{\"max_tokens\":32,\"messages\":[{\"content\":\"Count to three, one word per"
                  + " response.\",\"role\":\"user\"}],\"model\":\"vertex_ai/gemini-2.0-flash\",\"stream\":true}");

      assertEquals(200, resp.statusCode(), "HTTP status code");

      List<String> chunks = Helpers.parseSseChunks(resp.body());
      assertTrue(chunks.size() >= 3, "expected at least 3 chunk(s)");

      StringBuilder content = new StringBuilder();
      for (String rawChunk : chunks) {
        try {
          JsonNode chunk = Helpers.MAPPER.readTree(rawChunk);
          JsonNode deltaContent = chunk.at("/choices/0/delta/content");
          if (!deltaContent.isMissingNode() && deltaContent.isTextual()) {
            content.append(deltaContent.asText());
          }
        } catch (Exception ignored) {
          // Non-JSON chunks (role-only deltas etc.) are skipped.
        }
      }
      assertEquals("One Two Three", content.toString(), "stream content");
    }
  }
}
