// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public enum EmbeddingInput
{
    [JsonPropertyName("single")]
    Single,
    [JsonPropertyName("multiple")]
    Multiple,
}
