// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// A single generated image, returned as either a URL or base64 data.
/// </summary>
public sealed class Image
{
    [JsonPropertyName("url")]
    public string? Url { get; set; } = null;

    [JsonPropertyName("b64_json")]
    public string? B64Json { get; set; } = null;

    [JsonPropertyName("revised_prompt")]
    public string? RevisedPrompt { get; set; } = null;

}
