// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace LiterLlm;

public class LiterLlmException : Exception
{
    public int Code { get; }

    public LiterLlmException(int code, string message) : base(message)
    {
        Code = code;
    }
}
