// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// The text content of a reranked document, returned when `return_documents` is true.
/// </summary>
public sealed class RerankResultDocument
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
