// This file is auto-generated by alef. DO NOT EDIT.
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

[JsonConverter(typeof(ResponseFormatJsonConverter))]
public abstract record ResponseFormat
{
    public sealed record Text() : ResponseFormat;

    public sealed record JsonObject() : ResponseFormat;

    public sealed record JsonSchema(
        JsonSchemaFormat Value
    ) : ResponseFormat;

}

/// <summary>Custom JSON converter for <see cref="ResponseFormat"/> that reads the "type" discriminator from any position.</summary>
internal sealed class ResponseFormatJsonConverter : JsonConverter<ResponseFormat>
{
    public override ResponseFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        if (!root.TryGetProperty("type", out var tagEl))
            throw new JsonException("ResponseFormat: missing \"type\" discriminator");
        var tag = tagEl.GetString();
        var json = root.GetRawText();
        return tag switch
        {
            "text" => JsonSerializer.Deserialize<ResponseFormat.Text>(json, options)!
                ?? throw new JsonException("Failed to deserialize ResponseFormat.Text"),
            "json_object" => JsonSerializer.Deserialize<ResponseFormat.JsonObject>(json, options)!
                ?? throw new JsonException("Failed to deserialize ResponseFormat.JsonObject"),
            "json_schema" => new ResponseFormat.JsonSchema(
                JsonSerializer.Deserialize<JsonSchemaFormat>(json, options)!
                    ?? throw new JsonException("Failed to deserialize ResponseFormat.JsonSchema.Value")),
            _ => throw new JsonException($"Unknown ResponseFormat discriminator: {tag}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ResponseFormat value, JsonSerializerOptions options)
    {
        // Serialize the concrete type, then inject the discriminator
        switch (value)
        {
            case ResponseFormat.Text v:
                {
                    var doc = JsonSerializer.SerializeToDocument(v, options);
                    writer.WriteStartObject();
                    writer.WriteString("type", "text");
                    foreach (var prop in doc.RootElement.EnumerateObject())
                        if (prop.Name != "type") prop.WriteTo(writer);
                    writer.WriteEndObject();
                    break;
                }
            case ResponseFormat.JsonObject v:
                {
                    var doc = JsonSerializer.SerializeToDocument(v, options);
                    writer.WriteStartObject();
                    writer.WriteString("type", "json_object");
                    foreach (var prop in doc.RootElement.EnumerateObject())
                        if (prop.Name != "type") prop.WriteTo(writer);
                    writer.WriteEndObject();
                    break;
                }
            case ResponseFormat.JsonSchema v:
                {
                    var doc = JsonSerializer.SerializeToDocument(v.Value, options);
                    writer.WriteStartObject();
                    writer.WriteString("type", "json_schema");
                    foreach (var prop in doc.RootElement.EnumerateObject())
                        if (prop.Name != "type") prop.WriteTo(writer);
                    writer.WriteEndObject();
                    break;
                }
            default: throw new JsonException($"Unknown ResponseFormat subtype: {value.GetType().Name}");
        }
    }
}
