// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class UserMessage
{
    [JsonPropertyName("content")]
    public JsonElement Content { get; set; } = default;

    [JsonPropertyName("name")]
    public string? Name { get; set; } = null;

}
