from liter_lm._internal_bindings import (
    AssistantMessage,
    # Exceptions — specific
    AuthenticationError,
    BadRequestError,
    ChatCompletionChunk,
    ChatCompletionResponse,
    ChatStreamIterator,
    Choice,
    ContentPolicyError,
    ContextWindowExceededError,
    EmbeddingObject,
    EmbeddingResponse,
    EndpointNotSupportedError,
    FunctionCall,
    InvalidHeaderError,
    # Client
    LlmClient,
    # Exceptions — base
    LlmError,
    LlmTimeoutError,
    ModelObject,
    ModelsListResponse,
    NetworkError,
    NotFoundError,
    RateLimitedError,
    ServerError,
    ServiceUnavailableError,
    StreamChoice,
    StreamDelta,
    StreamFunctionCall,
    StreamingError,
    StreamToolCall,
    ToolCall,
    # Response types
    Usage,
    # Version
    __version__,
    _FinishReason,
)

# Request parameter TypedDicts are pure-Python constructs defined in _types.py.
# They are NOT part of the compiled Rust extension and must be imported from
# the pure-Python module to be available at runtime (not just in stubs).
from liter_lm._types import (
    ChatCompletionRequestParams,
    ContentPartImageParam,
    ContentPartParam,
    ContentPartTextParam,
    EmbeddingRequestParams,
    FunctionCallParam,
    FunctionDefinitionParam,
    ImageUrlParam,
    JsonSchemaParam,
    MessageParam,
    ResponseFormatJsonObjectParam,
    ResponseFormatJsonSchemaParam,
    ResponseFormatParam,
    ResponseFormatTextParam,
    SpecificFunctionParam,
    SpecificToolChoiceParam,
    StreamOptionsParam,
    ToolCallParam,
    ToolChoiceParam,
    ToolParam,
)

__all__ = [
    "AssistantMessage",
    "AuthenticationError",
    "BadRequestError",
    "ChatCompletionChunk",
    "ChatCompletionRequestParams",
    "ChatCompletionResponse",
    "ChatStreamIterator",
    "Choice",
    "ContentPartImageParam",
    "ContentPartParam",
    "ContentPartTextParam",
    "ContentPolicyError",
    "ContextWindowExceededError",
    "EmbeddingObject",
    "EmbeddingRequestParams",
    "EmbeddingResponse",
    "EndpointNotSupportedError",
    "FunctionCall",
    "FunctionCallParam",
    "FunctionDefinitionParam",
    "ImageUrlParam",
    "InvalidHeaderError",
    "JsonSchemaParam",
    # Client
    "LlmClient",
    # Exceptions
    "LlmError",
    "LlmTimeoutError",
    "MessageParam",
    "ModelObject",
    "ModelsListResponse",
    "NetworkError",
    "NotFoundError",
    "RateLimitedError",
    "ResponseFormatJsonObjectParam",
    "ResponseFormatJsonSchemaParam",
    "ResponseFormatParam",
    "ResponseFormatTextParam",
    "ServerError",
    "ServiceUnavailableError",
    "SpecificFunctionParam",
    "SpecificToolChoiceParam",
    "StreamChoice",
    "StreamDelta",
    "StreamFunctionCall",
    "StreamOptionsParam",
    "StreamToolCall",
    "StreamingError",
    "ToolCall",
    "ToolCallParam",
    "ToolChoiceParam",
    "ToolParam",
    # Response types
    "Usage",
    "_FinishReason",
    "__version__",
]
