# Code generated by liter-llm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

from typing import Any

import pytest


def assert_choices_count(response: Any, expected: int) -> None:
    """Assert the number of choices in a chat completion response."""
    actual = len(response.choices)
    if actual != expected:
        pytest.fail(f"Expected {expected} choice(s), got {actual}")


def assert_first_choice_content(response: Any, expected: str) -> None:
    """Assert the content of the first choice message."""
    actual = response.choices[0].message.content
    if actual != expected:
        pytest.fail(f"Expected first choice content {expected!r}, got {actual!r}")


def assert_usage(response: Any, field: str, expected: int) -> None:
    """Assert a specific usage field value."""
    usage = response.usage
    if usage is None:
        pytest.fail("Expected usage object but got None")
    actual = getattr(usage, field, None)
    if actual != expected:
        pytest.fail(f"Expected usage.{field} == {expected}, got {actual}")


def assert_model(response: Any, expected: str) -> None:
    """Assert the model identifier in the response."""
    actual = response.model
    if actual != expected:
        pytest.fail(f"Expected model {expected!r}, got {actual!r}")


def assert_error_type(error: Exception, expected: str) -> None:
    """Assert the error class name matches expected."""
    actual = type(error).__name__
    if actual != expected:
        pytest.fail(f"Expected error type {expected!r}, got {actual!r}")


def assert_stream_chunks(chunks: list[Any], min_count: int) -> None:
    """Assert a minimum number of stream chunks were received."""
    actual = len(chunks)
    if actual < min_count:
        pytest.fail(f"Expected at least {min_count} stream chunk(s), got {actual}")
