# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: rerank."""
import pytest
from liter_llm import chat, rerank


@pytest.mark.asyncio
async def test_edge_rerank_empty_query() -> None:
    """Reranking with an empty query string."""
    request = None
    result = await rerank(request=request)
    assert len(result.results) == 2  # noqa: S101

@pytest.mark.asyncio
async def test_edge_rerank_single_doc() -> None:
    """Reranking with only a single document."""
    request = None
    result = await rerank(request=request)
    assert len(result.results) == 1  # noqa: S101
    assert result.results.get("0").relevance_score > 0.9  # noqa: S101

@pytest.mark.asyncio
async def test_error_rerank_auth_401() -> None:
    """401 Unauthorized for reranking with invalid API key."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await rerank(request=request)
    assert "Authentication" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_error_rerank_bad_request() -> None:
    """400 Bad Request for reranking with invalid model."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await rerank(request=request)
    assert "InvalidRequest" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_smoke_rerank_basic() -> None:
    """Basic reranking of documents against a query."""
    request = None
    result = await rerank(request=request)
    assert len(result.results) == 3  # noqa: S101
    assert result.results.get("0").relevance_score > 0.9  # noqa: S101

@pytest.mark.asyncio
async def test_smoke_rerank_return_docs() -> None:
    """Reranking with return_documents flag to include document text."""
    request = None
    result = await rerank(request=request)
    assert len(result.results) == 2  # noqa: S101
    assert result.results.get("0").document  # noqa: S101
    assert result.results.get("0").relevance_score > 0.9  # noqa: S101

@pytest.mark.asyncio
async def test_smoke_rerank_with_top_n() -> None:
    """Reranking with top_n parameter to limit results."""
    request = None
    result = await rerank(request=request)
    assert len(result.results) == 2  # noqa: S101
    assert result.results.get("0").relevance_score > 0.9  # noqa: S101

