# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: image-generate."""
import pytest
from liter_llm import chat, image_generate


@pytest.mark.asyncio
async def test_edge_image_b64_response() -> None:
    """Image generation returning base64-encoded data instead of URL."""
    request = None
    result = await image_generate(request=request)
    assert len(result.data) == 1  # noqa: S101
    assert result.data.get("0").b64_json  # noqa: S101

@pytest.mark.asyncio
async def test_edge_image_empty_prompt() -> None:
    """Image generation with an empty prompt returns 400."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await image_generate(request=request)
    assert "InvalidRequest" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_error_image_auth_401() -> None:
    """401 Unauthorized when generating images with invalid API key."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await image_generate(request=request)
    assert "Authentication" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_error_image_bad_request() -> None:
    """400 Bad Request when image generation parameters are invalid."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await image_generate(request=request)
    assert "InvalidRequest" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_error_image_rate_limit() -> None:
    """429 Rate limit exceeded for image generation."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await image_generate(request=request)
    assert "RateLimited" in str(exc_info.value)  # noqa: S101

@pytest.mark.asyncio
async def test_smoke_image_basic() -> None:
    """Basic image generation with a text prompt."""
    request = None
    result = await image_generate(request=request)
    assert len(result.data) == 1  # noqa: S101
    assert result.data.get("0").url  # noqa: S101

@pytest.mark.asyncio
async def test_smoke_image_multiple() -> None:
    """Image generation requesting multiple images."""
    request = None
    result = await image_generate(request=request)
    assert len(result.data) == 3  # noqa: S101
    assert result.data.get("0").url  # noqa: S101

@pytest.mark.asyncio
async def test_smoke_image_with_size() -> None:
    """Image generation with explicit size parameter."""
    request = None
    result = await image_generate(request=request)
    assert len(result.data) == 1  # noqa: S101
    assert result.data.get("0").url  # noqa: S101

