# Code generated by liter-llm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import json

import pytest

from .mock_server import MockRoute, MockServerInfo
from liter_llm import BudgetExceededError, LlmClient


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 200, "{}"),
]], indirect=True)
async def test_budget_enforced(mock_server: MockServerInfo) -> None:
    """Tests that a request is rejected when budget is exceeded"""
    budget_config = json.loads("{\"enforcement\":\"hard\",\"global_limit\":0.0}")
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0, budget=budget_config)
    request = json.loads("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
    with pytest.raises(BudgetExceededError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 200, "{}"),
]], indirect=True)
async def test_budget_per_model(mock_server: MockServerInfo) -> None:
    """Tests per-model budget limit"""
    budget_config = json.loads("{\"enforcement\":\"hard\",\"model_limits\":{\"gpt-4\":0.0}}")
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0, budget=budget_config)
    request = json.loads("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
    with pytest.raises(BudgetExceededError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize("mock_server", [[
    MockRoute("/chat/completions", "POST", 200, "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\"Hello! How can I help you today?\",\"role\":\"assistant\"}}],\"created\":1711000000,\"id\":\"chatcmpl-budget-tracked-001\",\"model\":\"gpt-4\",\"object\":\"chat.completion\",\"usage\":{\"completion_tokens\":9,\"prompt_tokens\":8,\"total_tokens\":17}}"),
]], indirect=True)
async def test_budget_tracked(mock_server: MockServerInfo) -> None:
    """Tests that cost is tracked after a successful response"""
    budget_config = json.loads("{}")
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0, budget=budget_config)
    request = json.loads("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
    response = await client.chat(**request)
    assert response is not None
    # Verify cost was tracked after the request
    assert client.budget_used > 0, "Expected cost to be tracked"
