# Code generated by liter-llm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import pytest

from .mock_server import MockRoute, MockServerInfo
from liter_llm import (  # noqa: E402
    LlmClient,
    AuthenticationError,
    RateLimitedError,
    ServerError,
)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/chat/completions",
                "POST",
                401,
                '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided: sk-invalid. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_auth_invalid(mock_server: MockServerInfo) -> None:
    """401 Unauthorized when an invalid API key is provided through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}')
    with pytest.raises(AuthenticationError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/chat/completions",
                "POST",
                401,
                '{"error":{"code":null,"message":"You didn\'t provide an API key. You need to provide your API key in an Authorization header.","param":null,"type":"invalid_request_error"}}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_auth_missing(mock_server: MockServerInfo) -> None:
    """401 Unauthorized when no API key is provided through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}')
    with pytest.raises(AuthenticationError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/chat/completions",
                "POST",
                200,
                '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-proxy001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":3,"prompt_tokens":10,"total_tokens":13}}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_chat_basic(mock_server: MockServerInfo) -> None:
    """Basic chat completion request routed through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"messages":[{"content":"Say hello","role":"user"}],"model":"openai/gpt-4o"}')
    response = await client.chat(**request)

    assert len(response.choices) == 1, f"Expected 1 choice(s), got {len(response.choices)}"
    assert response.choices[0].message.content == "Hello!", "message content mismatch"
    assert response.choices[0].finish_reason == "stop", "finish_reason mismatch"
    assert response.usage is not None, "Expected usage object"
    assert response.usage.total_tokens == 13, "total_tokens mismatch"
    assert response.model == "gpt-4o", "model mismatch"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/chat/completions",
                "POST",
                200,
                stream_chunks=[
                    '{"choices":[{"delta":{"content":"","role":"assistant"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":"1"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":" 2"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{"content":" 3"},"finish_reason":null,"index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                    '{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1711000000,"id":"chatcmpl-proxystream001","model":"gpt-4o","object":"chat.completion.chunk"}',
                ],
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_chat_streaming(mock_server: MockServerInfo) -> None:
    """Streaming chat completion routed through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"messages":[{"content":"Count to 3","role":"user"}],"model":"openai/gpt-4o","stream":true}')
    chunks = []
    async for chunk in await client.chat_stream(**request):
        chunks.append(chunk)
    assert len(chunks) >= 3, f"Expected at least 3 chunk(s), got {len(chunks)}"
    content = "".join(c.choices[0].delta.content or "" for c in chunks if c.choices)
    assert content == "1 2 3", f"Stream content mismatch: {content!r}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/embeddings",
                "POST",
                200,
                '{"data":[{"embedding":[0.01,0.02,0.03,0.04,0.05],"index":0,"object":"embedding"}],"model":"text-embedding-3-small","object":"list","usage":{"completion_tokens":0,"prompt_tokens":2,"total_tokens":2}}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_embeddings(mock_server: MockServerInfo) -> None:
    """Embedding request routed through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"input":"Hello world","model":"openai/text-embedding-3-small"}')
    response = await client.embed(**request)

    assert len(response.data) == 1, f"Expected 1 embedding(s), got {len(response.data)}"
    assert len(response.data[0].embedding) == 5, f"Expected 5 dimensions, got {len(response.data[0].embedding)}"
    assert len(response.data) >= 1, f"Expected at least 1 embedding(s), got {len(response.data)}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/models",
                "GET",
                200,
                '{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"}],"object":"list"}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_health(mock_server: MockServerInfo) -> None:
    """Health check verifying proxy connectivity via list models"""
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    response = await client.list_models()

    assert len(response.data) == 1, f"Expected 1 model(s), got {len(response.data)}"
    assert len(response.data) >= 1, f"Expected at least 1 model(s), got {len(response.data)}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/models",
                "GET",
                200,
                '{"data":[{"created":1715367049,"id":"gpt-4o","object":"model","owned_by":"openai"},{"created":1721172741,"id":"gpt-4o-mini","object":"model","owned_by":"openai"}],"object":"list"}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_models_list(mock_server: MockServerInfo) -> None:
    """List models request routed through the proxy"""
    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    response = await client.list_models()

    assert len(response.data) == 2, f"Expected 2 model(s), got {len(response.data)}"
    assert len(response.data) >= 1, f"Expected at least 1 model(s), got {len(response.data)}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/chat/completions",
                "POST",
                429,
                '{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4o in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_upstream_429(mock_server: MockServerInfo) -> None:
    """429 Too Many Requests from upstream provider through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}')
    with pytest.raises(RateLimitedError):
        await client.chat(**request)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "mock_server",
    [
        [
            MockRoute(
                "/chat/completions",
                "POST",
                500,
                '{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}',
            ),
        ]
    ],
    indirect=True,
)
async def test_proxy_upstream_500(mock_server: MockServerInfo) -> None:
    """500 Internal Server Error from upstream provider through the proxy"""
    import json

    client = LlmClient(api_key="test-key", base_url=mock_server.url, max_retries=0)
    request = json.loads('{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}')
    with pytest.raises(ServerError):
        await client.chat(**request)
