// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** E2e tests for category: image-generate. */
class ImageGenerateTest {
    @Test
    void testEdgeImageB64Response() throws Exception {
        // Image generation returning base64-encoded data instead of URL
        var result = LiterLlm.chat(null);
        // TODO: unsupported assertion type: count_equals
        assertFalse(result.data().get("0").b64Json().isEmpty(), "expected non-empty value");
    }

    @Test
    void testEdgeImageEmptyPrompt() throws Exception {
        // Image generation with an empty prompt returns 400
        assertThrows(Exception.class, () -> LiterLlm.chat(null));
    }

    @Test
    void testErrorImageAuth401() throws Exception {
        // 401 Unauthorized when generating images with invalid API key
        assertThrows(Exception.class, () -> LiterLlm.chat(null));
    }

    @Test
    void testErrorImageBadRequest() throws Exception {
        // 400 Bad Request when image generation parameters are invalid
        assertThrows(Exception.class, () -> LiterLlm.chat(null));
    }

    @Test
    void testErrorImageRateLimit() throws Exception {
        // 429 Rate limit exceeded for image generation
        assertThrows(Exception.class, () -> LiterLlm.chat(null));
    }

    @Test
    void testSmokeImageBasic() throws Exception {
        // Basic image generation with a text prompt
        var result = LiterLlm.chat(null);
        // TODO: unsupported assertion type: count_equals
        assertFalse(result.data().get("0").url().isEmpty(), "expected non-empty value");
    }

    @Test
    void testSmokeImageMultiple() throws Exception {
        // Image generation requesting multiple images
        var result = LiterLlm.chat(null);
        // TODO: unsupported assertion type: count_equals
        assertFalse(result.data().get("0").url().isEmpty(), "expected non-empty value");
    }

    @Test
    void testSmokeImageWithSize() throws Exception {
        // Image generation with explicit size parameter
        var result = LiterLlm.chat(null);
        // TODO: unsupported assertion type: count_equals
        assertFalse(result.data().get("0").url().isEmpty(), "expected non-empty value");
    }

}
