#!/usr/bin/env bash
# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: custom_provider
set -euo pipefail

test_provider_auth() {
    # Tests custom provider with custom auth header
    local output
    output=$(liter_llm chat)

}

test_register_provider() {
    # Tests that a custom provider can be registered and routes requests
    local output
    output=$(liter_llm chat)

}

run_tests_custom_provider() {
    run_test test_provider_auth
    run_test test_register_provider
}
