# This file is auto-generated by alef. DO NOT EDIT.
defmodule LiterLlm.CustomProviderConfig do
  @moduledoc "Configuration for registering a custom LLM provider at runtime."

  defstruct name: "",
            base_url: "",
            auth_header: :bearer,
            model_prefixes: []
end
