# This file is auto-generated by alef. DO NOT EDIT.
defmodule LiterLlm.RerankRequest do
  @moduledoc "Request to rerank documents by relevance to a query."

  defstruct model: "",
            query: "",
            documents: [],
            top_n: nil,
            return_documents: nil
end
