# This file is auto-generated by alef. DO NOT EDIT.
defmodule LiterLlm.TranscriptionSegment do
  @moduledoc "A segment of transcribed audio with timing information."

  defstruct id: 0,
            start: 0.0,
            end: 0.0,
            text: ""
end
