// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: parity.</summary>
public class ParityTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_ApiSurfaceParity()
    {
        // Canonical API surface definition for cross-binding parity verification
        var result = await LiterLlmLib.Chat(null);
    }
}
