# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: hooks."""
import pytest
from liter_llm import chat


@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_hook_guardrail() -> None:
    """Tests that on_request hook can reject a request."""
    request = None
    with pytest.raises(Exception) as exc_info:
        await chat(request=request)
    assert "HookRejected" in str(exc_info.value)  # noqa: S101

@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_hook_on_error() -> None:
    """Tests that on_error hook is called on failure."""
    request = None
    result = await chat(request=request)
    # TODO: unsupported assertion type: is_true

@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_hook_on_request() -> None:
    """Tests that on_request hook is called before the request."""
    request = None
    result = await chat(request=request)
    # TODO: unsupported assertion type: is_true

@pytest.mark.skip(reason="skipped for python")
@pytest.mark.asyncio
async def test_hook_on_response() -> None:
    """Tests that on_response hook is called with response data."""
    request = None
    result = await chat(request=request)
    # TODO: unsupported assertion type: is_true

