// Code generated by liter-llm-e2e-generator. DO NOT EDIT.
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		globals: false,
		environment: "node",
		testTimeout: 10000,
	},
});
