// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Map;
import java.util.Optional;

public class BudgetConfigBuilder {

    private Optional<Double> globalLimit = Optional.empty();
    private Map<String, Double> modelLimits = Map.of();
    private Enforcement enforcement = null;

    public BudgetConfigBuilder withGlobalLimit(Optional<Double> value) {
        this.globalLimit = value;
        return this;
    }

    public BudgetConfigBuilder withModelLimits(Map<String, Double> value) {
        this.modelLimits = value;
        return this;
    }

    public BudgetConfigBuilder withEnforcement(Enforcement value) {
        this.enforcement = value;
        return this;
    }

    public BudgetConfig build() {
        return new BudgetConfig(
            globalLimit,
            modelLimits,
            enforcement
        );
    }
}
