// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum CacheBackend {
    Memory("memory"),
    OpenDal("opendal");

    private final String value;

    CacheBackend(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static CacheBackend fromValue(String value) {
        for (CacheBackend e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
