// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;


public class CacheConfigBuilder {

    private long maxEntries = 0;
    private Long ttl = null;
    private CacheBackend backend = null;

    public CacheConfigBuilder withMaxEntries(long value) {
        this.maxEntries = value;
        return this;
    }

    public CacheConfigBuilder withTtl(Long value) {
        this.ttl = value;
        return this;
    }

    public CacheConfigBuilder withBackend(CacheBackend value) {
        this.backend = value;
        return this;
    }

    public CacheConfig build() {
        return new CacheConfig(
            maxEntries,
            ttl,
            backend
        );
    }
}
