// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

public class ChatCompletionResponseBuilder {

    private String id = "";
    private String object = "";
    private long created = 0;
    private String model = "";
    private List<Choice> choices = List.of();
    private Optional<Usage> usage = Optional.empty();
    private Optional<String> systemFingerprint = Optional.empty();
    private Optional<String> serviceTier = Optional.empty();

    public ChatCompletionResponseBuilder withId(String value) {
        this.id = value;
        return this;
    }

    public ChatCompletionResponseBuilder withObject(String value) {
        this.object = value;
        return this;
    }

    public ChatCompletionResponseBuilder withCreated(long value) {
        this.created = value;
        return this;
    }

    public ChatCompletionResponseBuilder withModel(String value) {
        this.model = value;
        return this;
    }

    public ChatCompletionResponseBuilder withChoices(List<Choice> value) {
        this.choices = value;
        return this;
    }

    public ChatCompletionResponseBuilder withUsage(Optional<Usage> value) {
        this.usage = value;
        return this;
    }

    public ChatCompletionResponseBuilder withSystemFingerprint(Optional<String> value) {
        this.systemFingerprint = value;
        return this;
    }

    public ChatCompletionResponseBuilder withServiceTier(Optional<String> value) {
        this.serviceTier = value;
        return this;
    }

    public ChatCompletionResponse build() {
        return new ChatCompletionResponse(
            id,
            object,
            created,
            model,
            choices,
            usage,
            systemFingerprint,
            serviceTier
        );
    }
}
