// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

public record ChatCompletionTool(
    @JsonProperty("tool_type") ToolType toolType,
    FunctionDefinition function
) {
}
