// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

public class ContentPolicyException extends LiterLlmErrorException {
    public ContentPolicyException(String message) {
        super(message);
    }

    public ContentPolicyException(String message, Throwable cause) {
        super(message, cause);
    }
}
