// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record EmbeddingRequest(
    String model,
    Object input,
    @JsonProperty("encoding_format") Optional<EmbeddingFormat> encodingFormat,
    Optional<Integer> dimensions,
    Optional<String> user
) {
}
