// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Optional;

public record FileListQuery(
    Optional<String> purpose,
    Optional<Integer> limit,
    Optional<String> after
) {
    public static FileListQueryBuilder builder() {
        return new FileListQueryBuilder();
    }
}
