// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum FinishReason {
    Stop("stop"),
    Length("length"),
    ToolCalls("tool_calls"),
    ContentFilter("content_filter"),
    FunctionCall("function_call"),
    Other("other");

    private final String value;

    FinishReason(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static FinishReason fromValue(String value) {
        for (FinishReason e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
