// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;

public record ModelPricing(
    @JsonProperty("input_cost_per_token") double inputCostPerToken,
    @JsonProperty("output_cost_per_token") double outputCostPerToken
) {
}
