// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

public class RateLimitedException extends LiterLlmErrorException {
    public RateLimitedException(String message) {
        super(message);
    }

    public RateLimitedException(String message, Throwable cause) {
        super(message, cause);
    }
}
