// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record RerankResult(
    int index,
    @JsonProperty("relevance_score") double relevanceScore,
    Optional<RerankResultDocument> document
) {
}
