// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;

public record TranscriptionResponse(
    String text,
    Optional<String> language,
    Optional<Double> duration,
    Optional<List<TranscriptionSegment>> segments
) {
    public static TranscriptionResponseBuilder builder() {
        return new TranscriptionResponseBuilder();
    }
}
