// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

using System.Text.Json;
using System.Net.Http;
using Xunit;

namespace LiterLlmE2E;

public sealed class EmbedTests
{

    /// <summary>Embedding request with multiple input strings returns one embedding object per input</summary>
    [Fact]
    public async Task BatchEmbed()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/embeddings",
                Method: "POST",
                Status: 200,
                Body: "{\"data\":[{\"embedding\":[0.1,0.2,0.3,0.4,0.5],\"index\":0,\"object\":\"embedding\"},{\"embedding\":[0.5,0.4,0.3,0.2,0.1],\"index\":1,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"input\":[\"Hello\",\"World\"],\"model\":\"text-embedding-3-small\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/embeddings", content);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(2, doc.GetProperty("data").GetArrayLength());
    }

    /// <summary>Embedding request with explicit encoding_format of float returns float array embeddings</summary>
    [Fact]
    public async Task EmbedEncodingFormat()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/embeddings",
                Method: "POST",
                Status: 200,
                Body: "{\"data\":[{\"embedding\":[0.123,0.456,0.789,0.012,0.345],\"index\":0,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"encoding_format\":\"float\",\"input\":\"Test input\",\"model\":\"text-embedding-3-small\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/embeddings", content);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(1, doc.GetProperty("data").GetArrayLength());
    }

    /// <summary>401 Unauthorized error on embedding request when API key is invalid</summary>
    [Fact]
    public async Task EmbedError401()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/embeddings",
                Method: "POST",
                Status: 401,
                Body: "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API key provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/embeddings", content);
        Assert.Equal(401, (int)response.StatusCode);
    }

    /// <summary>Embedding request with explicit dimensions parameter returns embeddings of the requested size</summary>
    [Fact]
    public async Task EmbedWithDimensions()
    {
        var routes = new[]
        {
            new MockRoute(
                Path: "/embeddings",
                Method: "POST",
                Status: 200,
                Body: "{\"data\":[{\"embedding\":[0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08],\"index\":0,\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\",\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_tokens\":2,\"total_tokens\":2}}",
                StreamChunks: Array.Empty<string>()
            ),
        };

        using var server = new MockServer(routes);
        using var http = new HttpClient();
        http.BaseAddress = new Uri(server.Url);

        var content = new StringContent("{\"dimensions\":256,\"input\":\"Hello world\",\"model\":\"text-embedding-3-small\"}", System.Text.Encoding.UTF8, "application/json");
        var response = await http.PostAsync("/embeddings", content);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadAsStringAsync();
        var doc = JsonDocument.Parse(body).RootElement;

        Assert.Equal(1, doc.GetProperty("data").GetArrayLength());
    }
}
