# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: contract
defmodule E2e.ContractTest do
  use ExUnit.Case, async: true

  describe "binding_api_parity" do
    test "Verify all bindings expose the full API surface — constructor accepts all config options and every method exists" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "OK"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert result.usage.total_tokens == 6
      assert String.trim(result.model) == "gpt-4o"
    end
  end

  describe "contract_ocr" do
    test "Verify ocr() method exists in all bindings" do
      {:ok, result} = LiterLlm.chat_async(nil)
    end
  end

  describe "contract_search" do
    test "Verify search() method exists in all bindings" do
      {:ok, result} = LiterLlm.chat_async(nil)
    end
  end
end
