# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: moderate
defmodule E2e.ModerateTest do
  use ExUnit.Case, async: true

  describe "edge_moderate_all_categories" do
    test "Moderation response with multiple categories flagged" do
      {:ok, result} = LiterLlm.chat_async("Extremely harmful content targeting multiple categories")
      # TODO: unsupported assertion type: count_equals
      assert result.results["0"].flagged == true
    end
  end

  describe "edge_moderate_empty_input" do
    test "Moderation with empty string input" do
      {:ok, result} = LiterLlm.chat_async("")
      # TODO: unsupported assertion type: count_equals
      assert result.results["0"].flagged == false
    end
  end

  describe "error_moderate_auth_401" do
    test "401 Unauthorized for moderation with invalid API key" do
      assert {:error, _} = LiterLlm.chat_async("Hello")
    end
  end

  describe "error_moderate_bad_request" do
    test "400 Bad Request for moderation with invalid model" do
      assert {:error, _} = LiterLlm.chat_async("Hello")
    end
  end

  describe "smoke_moderate_batch" do
    test "Moderate multiple inputs in a single request" do
      {:ok, result} = LiterLlm.chat_async(["Hello world", "Nice weather today"])
      # TODO: unsupported assertion type: count_equals
      assert result.results["0"].flagged == false
    end
  end

  describe "smoke_moderate_flagged" do
    test "Moderation detects flagged content" do
      {:ok, result} = LiterLlm.chat_async("I want to hurt someone very badly")
      # TODO: unsupported assertion type: count_equals
      assert result.results["0"].flagged == true
    end
  end

  describe "smoke_moderate_single" do
    test "Moderate a single non-flagged input" do
      {:ok, result} = LiterLlm.chat_async("The weather is nice today.")
      # TODO: unsupported assertion type: count_equals
      assert result.results["0"].flagged == false
    end
  end
end
