# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: ocr
defmodule E2e.OcrTest do
  use ExUnit.Case, async: true

  describe "ocr_url_document" do
    test "OCR request with a document URL input" do
      {:ok, result} = LiterLlm.chat_async(nil)
    end
  end
end
