# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: smoke
defmodule E2e.SmokeTest do
  use ExUnit.Case, async: true

  describe "anthropic_chat" do
    test "Basic chat completion via the Anthropic provider (claude-3-5-sonnet-20241022) with system and user messages" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "Hello!"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert String.trim(result.model) == "claude-3-5-sonnet-20241022"
      assert result.usage.total_tokens == 23
    end
  end

  describe "azure_chat" do
    test "Chat completion via Azure OpenAI with the azure/ prefix for provider routing — verifies the prefix is stripped before dispatching and the response is normalised to the standard OpenAI chat completion shape" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "Hello!"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert String.trim(result.model) == "gpt-4"
      assert result.usage.total_tokens == 13
    end
  end

  describe "azure_embed" do
    test "Embedding request via Azure OpenAI using the azure/ provider prefix — response follows the standard OpenAI embeddings shape that Azure returns unchanged" do
      {:ok, result} = LiterLlm.chat_async("Hello world")
      # TODO: unsupported assertion type: count_equals
      # TODO: unsupported assertion type: count_equals
    end
  end

  describe "basic_chat" do
    test "Basic chat completion with a single user message" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "Hello!"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert result.usage.total_tokens == 15
      assert String.trim(result.model) == "gpt-4"
    end
  end

  describe "basic_embed" do
    test "Basic embedding request for a single input string" do
      {:ok, result} = LiterLlm.chat_async("Hello world")
      # TODO: unsupported assertion type: count_equals
      # TODO: unsupported assertion type: count_equals
    end
  end

  describe "basic_list_models" do
    test "List available models from the API" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert length(result.data) >= 1
    end
  end

  describe "bedrock_chat" do
    test "Basic chat completion via the AWS Bedrock provider using the bedrock/ prefix for routing — verifies the prefix is stripped before dispatching and the Converse API response is normalised to the standard OpenAI chat completion shape" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "Hello!"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert String.trim(result.model) == "anthropic.claude-3-sonnet-20240229-v1:0"
      assert result.usage.total_tokens == 15
    end
  end

  describe "github_copilot_chat" do
    test "Basic chat completion via the GitHub Copilot provider (gpt-4o) with a single user message" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "Hello!"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert String.trim(result.model) == "gpt-4o"
      assert result.usage.total_tokens == 14
    end
  end

  describe "local_chat_ollama" do
    test "Chat completion against local Ollama with qwen2:0.5b model" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert result.choices != ""
    end
  end

  describe "local_list_models_ollama" do
    test "List models from local Ollama instance" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert length(result.data) >= 1
    end
  end

  describe "smoke_cache_memory" do
    test "Test in-memory caching by sending identical requests twice" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert result.choices != ""
    end
  end

  describe "smoke_chat_anthropic" do
    test "Basic chat completion against real Anthropic API" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert result.choices != ""
      assert result.usage != ""
    end
  end

  describe "smoke_chat_gemini" do
    test "Basic chat completion against real Google Gemini API" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert result.choices != ""
      assert result.usage != ""
    end
  end

  describe "smoke_chat_openai" do
    test "Basic chat completion against real OpenAI API" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert result.choices != ""
      assert result.usage != ""
    end
  end

  describe "smoke_embed_openai" do
    test "Embeddings request against real OpenAI API" do
      {:ok, result} = LiterLlm.chat_async(["Hello world"])
      assert result.data != ""
    end
  end

  describe "smoke_list_models_openai" do
    test "List models against real OpenAI API" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert length(result.data) >= 1
    end
  end

  describe "smoke_provider_routing" do
    test "Test provider routing by sending requests to OpenAI and Anthropic" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert result.choices != ""
    end
  end

  describe "smoke_streaming_openai" do
    test "Chat streaming against real OpenAI API, verifies chunks received" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert length(result.chunks) >= 1
    end
  end

  describe "vertex_chat" do
    test "Basic chat completion via the Google Vertex AI provider using the vertex_ai/ prefix for routing — verifies the prefix is stripped before dispatching and the Gemini response is normalised to the standard OpenAI chat completion shape" do
      {:ok, result} = LiterLlm.chat_async(nil)
      # TODO: unsupported assertion type: count_equals
      assert String.trim(result.choices["0"].message.content) == "Hello!"
      assert String.trim(result.choices["0"].finish_reason) == "stop"
      assert String.trim(result.model) == "gemini-2.0-flash"
      assert result.usage.total_tokens == 13
    end
  end

  describe "vertex_embed" do
    test "Embedding request via Google Vertex AI using the vertex_ai/ provider prefix and the text-embedding-005 model — response follows the standard OpenAI embeddings shape" do
      {:ok, result} = LiterLlm.chat_async("Hello")
      # TODO: unsupported assertion type: count_equals
      # TODO: unsupported assertion type: count_equals
    end
  end
end
