# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: transcribe
defmodule E2e.TranscribeTest do
  use ExUnit.Case, async: true

  describe "edge_transcribe_empty_audio" do
    test "Transcription of a silent or empty audio file returns empty text" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert String.contains?(to_string(result.text), "")
    end
  end

  describe "error_transcribe_auth_401" do
    test "401 Unauthorized for transcription with invalid API key" do
      assert {:error, _} = LiterLlm.chat_async(nil)
    end
  end

  describe "error_transcribe_bad_format" do
    test "400 Bad Request when audio format is unsupported" do
      assert {:error, _} = LiterLlm.chat_async(nil)
    end
  end

  describe "smoke_transcribe_basic" do
    test "Basic audio transcription" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert String.contains?(to_string(result.text), "Hello, this is a test transcription.")
    end
  end

  describe "smoke_transcribe_with_language" do
    test "Audio transcription with explicit language hint" do
      {:ok, result} = LiterLlm.chat_async(nil)
      assert String.contains?(to_string(result.text), "Hallo, dies ist ein Testtranskription.")
    end
  end
end
