# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "error-handling" do
  it "anthropic_error_auth" do
    # 401 Authentication error returned by the Anthropic API when the API key is invalid
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 401,
      body: '{"error":{"message":"invalid x-api-key","type":"authentication_error"},"type":"error"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"anthropic/claude-3-5-sonnet-20241022"}')

    expect(response.code.to_i).to eq(401)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "auth_401" do
    # 401 Unauthorized error when API key is invalid or missing
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 401,
      body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(401)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "azure_error_auth" do
    # Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 401,
      body: '{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"azure/gpt-4"}')

    expect(response.code.to_i).to eq(401)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "bad_request_400" do
    # 400 Bad Request error when a parameter value is invalid
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 400,
      body: '{"error":{"message":"Invalid parameter: temperature must be between 0 and 2","type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4","temperature":5.0}')

    expect(response.code.to_i).to eq(400)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "content_policy_violation" do
    # 400 error when a request is rejected due to content policy
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 400,
      body: '{"error":{"message":"Your request was rejected as a result of our content_policy","type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Generate harmful content","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(400)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "context_window_exceeded" do
    # 400 error when the prompt exceeds the model's maximum context length
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 400,
      body: "{\"error\":{\"code\":\"context_length_exceeded\",\"message\":\"This model's maximum context length is 8192 tokens\",\"type\":\"invalid_request_error\"}}",
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Very long prompt that exceeds the context window...","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(400)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "forbidden_403" do
    # 403 Forbidden error when the API key does not have access to the requested resource
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 403,
      body: '{"error":{"message":"Access denied","type":"access_denied"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(403)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "gateway_timeout_504" do
    # 504 Gateway Timeout error when the upstream service times out
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 504,
      body: '{"error":{"message":"Gateway timeout","type":"server_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(504)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "not_found_404" do
    # 404 Not Found error when requesting a model that does not exist
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 404,
      body: '{"error":{"message":"Model not found","type":"not_found_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-99"}')

    expect(response.code.to_i).to eq(404)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "rate_limit_429" do
    # 429 Too Many Requests error when the rate limit is exceeded
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 429,
      body: '{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(429)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "server_error_500" do
    # 500 Internal Server Error from the upstream API
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 500,
      body: '{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(500)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

  it "service_unavailable_502" do
    # 502 Bad Gateway error when the upstream service is unavailable
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 502,
      body: '{"error":{"message":"Bad gateway","type":"server_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}')

    expect(response.code.to_i).to eq(502)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

end
