# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "list-models" do
  it "empty_model_list" do
    # List models response returns an empty data array when no models are available
    route = E2EHelpers::MockRoute.new(
      path: "/models",
      method: "GET",
      status: 200,
      body: '{"data":[],"object":"list"}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = get_json(server.url, "/models")

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)
    expect(body["data"].size).to eq(0)

  ensure
    server&.stop
  end

  it "list_models_error_401" do
    # 401 Unauthorized error on list models request when API key is invalid
    route = E2EHelpers::MockRoute.new(
      path: "/models",
      method: "GET",
      status: 401,
      body: '{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = get_json(server.url, "/models")

    expect(response.code.to_i).to eq(401)
    expect(response.code.to_i).to be >= 400

  ensure
    server&.stop
  end

end
