# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require 'spec_helper'

RSpec.describe 'search' do
  it 'search_basic' do
    # Basic web search request with a simple query
    route = E2EHelpers::MockRoute.new(
      path: '/chat/completions',
      method: 'POST',
      status: 200,
      body: '{"model":"brave/web-search","results":[{"snippet":"A language empowering everyone to build reliable and efficient software.","title":"Rust Programming Language","url":"https://www.rust-lang.org"}]}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    # TODO: unknown method "search"
  ensure
    server&.stop
  end
end
