# Code generated by liter-llm-e2e-generator. DO NOT EDIT.
# frozen_string_literal: true

require "spec_helper"

RSpec.describe "types" do
  it "all_message_types" do
    # Request with all message role types (system, user, assistant, tool) to verify round-trip serialization
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 200,
      body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"The weather in Paris is currently 18°C and partly cloudy.","role":"assistant"}}],"created":1711000003,"id":"chatcmpl-types001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":18,"prompt_tokens":95,"total_tokens":113}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", "{\"messages\":[{\"content\":\"You are a helpful assistant.\",\"role\":\"system\"},{\"content\":\"What is the weather in Paris?\",\"role\":\"user\"},{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\": \\\"Paris, France\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_xyz789\",\"type\":\"function\"}]},{\"content\":\"{\\\"temperature\\\": 18, \\\"unit\\\": \\\"celsius\\\", \\\"description\\\": \\\"Partly cloudy\\\"}\",\"role\":\"tool\",\"tool_call_id\":\"call_xyz789\"}],\"model\":\"gpt-4\"}")

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)

    expect(body["choices"].size).to eq(1)
    expect(body.dig("choices", 0, "message", "content")).to eq('The weather in Paris is currently 18°C and partly cloudy.')
    expect(body.dig("choices", 0, "finish_reason")).to eq('stop')
    expect(body["model"]).to eq('gpt-4')
    expect(body["usage"]).not_to be_nil
    expect(body.dig("usage", "total_tokens")).to eq(113)

  ensure
    server&.stop
  end

  it "multimodal_content" do
    # User message with mixed text and image_url content parts to verify multimodal serialization
    route = E2EHelpers::MockRoute.new(
      path: "/chat/completions",
      method: "POST",
      status: 200,
      body: '{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"The image shows a transparent PNG demonstration with colored dice.","role":"assistant"}}],"created":1711000004,"id":"chatcmpl-multi001","model":"gpt-4o","object":"chat.completion","usage":{"completion_tokens":14,"prompt_tokens":855,"total_tokens":869}}',
      stream_chunks: []
    )
    server = E2EHelpers::MockServer.new([route])

    response = post_json(server.url, "/chat/completions", '{"max_tokens":100,"messages":[{"content":[{"text":"What is in this image?","type":"text"},{"image_url":{"detail":"low","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png"},"type":"image_url"}],"role":"user"}],"model":"gpt-4o"}')

    expect(response.code.to_i).to eq(200)

    body = JSON.parse(response.body)

    expect(body["choices"].size).to eq(1)
    expect(body.dig("choices", 0, "message", "content")).to eq('The image shows a transparent PNG demonstration with colored dice.')
    expect(body.dig("choices", 0, "finish_reason")).to eq('stop')
    expect(body["model"]).to eq('gpt-4o')
    expect(body["usage"]).not_to be_nil
    expect(body.dig("usage", "total_tokens")).to eq(869)

  ensure
    server&.stop
  end

end
