/* Code generated by liter-llm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* 401 Unauthorized when an invalid API key is provided through the proxy */
static void test_proxy_auth_invalid(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API "
      "key provided: sk-invalid. You can find your API key at "
      "https://platform.openai.com/account/"
      "api-keys.\",\"param\":null,\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],"
             "\"model\":\"openai/gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 401L, "test_proxy_auth_invalid");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 401 Unauthorized when no API key is provided through the proxy */
static void test_proxy_auth_missing(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":null,\"message\":\"You didn't provide an API key. "
      "You need to provide your API key in an Authorization "
      "header.\",\"param\":null,\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],"
             "\"model\":\"openai/gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 401L, "test_proxy_auth_missing");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Basic chat completion request routed through the proxy */
static void test_proxy_chat_basic(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{"
      "\"content\":\"Hello!\",\"role\":\"assistant\"}}],\"created\":1711000000,"
      "\"id\":\"chatcmpl-proxy001\",\"model\":\"gpt-4o\",\"object\":\"chat."
      "completion\",\"usage\":{\"completion_tokens\":3,\"prompt_tokens\":10,"
      "\"total_tokens\":13}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Say "
             "hello\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_chat_basic");
    liter_llm_assert_json_array_len(resp->body, "choices", 1,
                                    "test_proxy_chat_basic");
    liter_llm_assert_json_field(resp->body, "content", "Hello!",
                                "test_proxy_chat_basic");
    liter_llm_assert_json_field(resp->body, "model", "gpt-4o",
                                "test_proxy_chat_basic");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_llm_assert_json_array_len(mock_body, "choices", 1,
                                    "test_proxy_chat_basic");
    liter_llm_assert_json_field(mock_body, "content", "Hello!",
                                "test_proxy_chat_basic");
    liter_llm_assert_json_field(mock_body, "model", "gpt-4o",
                                "test_proxy_chat_basic");
  }
}

/* Streaming chat completion routed through the proxy */
static void test_proxy_chat_streaming(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Count to "
        "3\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o\",\"stream\":true}",
        chunks, 256);
    if (n < 3) {
      fprintf(
          stderr,
          "FAIL [test_proxy_chat_streaming]: expected >= 3 chunks, got %d\n",
          n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Embedding request routed through the proxy */
static void test_proxy_embeddings(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"data\":[{\"embedding\":[0.01,0.02,0.03,0.04,0.05],\"index\":0,"
      "\"object\":\"embedding\"}],\"model\":\"text-embedding-3-small\","
      "\"object\":\"list\",\"usage\":{\"completion_tokens\":0,\"prompt_"
      "tokens\":2,\"total_tokens\":2}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/embeddings", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"input\":\"Hello "
             "world\",\"model\":\"openai/text-embedding-3-small\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_embeddings");
    liter_llm_assert_json_array_len(resp->body, "data", 1,
                                    "test_proxy_embeddings");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_llm_assert_json_array_len(mock_body, "data", 1,
                                    "test_proxy_embeddings");
  }
}

/* Health check verifying proxy connectivity via list models */
static void test_proxy_health(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"data\":[{\"created\":1715367049,\"id\":\"gpt-4o\",\"object\":"
      "\"model\",\"owned_by\":\"openai\"}],\"object\":\"list\"}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/models", base_url);

    LiterLlmResponse *resp = liter_llm_http_get(url);
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_health");
    liter_llm_assert_json_array_len(resp->body, "data", 1, "test_proxy_health");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_llm_assert_json_array_len(mock_body, "data", 1, "test_proxy_health");
  }
}

/* Image generation request routed through the proxy */
static void test_proxy_image_generate(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"created\":1711000000,\"data\":[{\"revised_prompt\":\"A vivid sunset "
      "casting warm orange and pink hues over a calm "
      "ocean\",\"url\":\"https://example.com/images/img-proxy001.png\"}]}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/images/generations", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A sunset over the "
             "ocean\",\"size\":\"1024x1024\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_image_generate");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* List models request routed through the proxy */
static void test_proxy_models_list(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"data\":[{\"created\":1715367049,\"id\":\"gpt-4o\",\"object\":"
      "\"model\",\"owned_by\":\"openai\"},{\"created\":1721172741,\"id\":\"gpt-"
      "4o-mini\",\"object\":\"model\",\"owned_by\":\"openai\"}],\"object\":"
      "\"list\"}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/models", base_url);

    LiterLlmResponse *resp = liter_llm_http_get(url);
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_models_list");
    liter_llm_assert_json_array_len(resp->body, "data", 2,
                                    "test_proxy_models_list");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_llm_assert_json_array_len(mock_body, "data", 2,
                                    "test_proxy_models_list");
  }
}

/* Content moderation request routed through the proxy */
static void test_proxy_moderation(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"id\":\"modr-proxy001\",\"model\":\"omni-moderation-latest\","
      "\"results\":[{\"categories\":{\"harassment\":false,\"harassment/"
      "threatening\":false,\"hate\":false,\"hate/"
      "threatening\":false,\"self-harm\":false,\"self-harm/"
      "instructions\":false,\"self-harm/"
      "intent\":false,\"sexual\":false,\"sexual/"
      "minors\":false,\"violence\":false,\"violence/"
      "graphic\":false},\"category_scores\":{\"harassment\":0.0002,"
      "\"harassment/threatening\":0.0001,\"hate\":0.0001,\"hate/"
      "threatening\":0.0001,\"self-harm\":0.0001,\"self-harm/"
      "instructions\":0.0001,\"self-harm/"
      "intent\":0.0001,\"sexual\":0.0001,\"sexual/"
      "minors\":0.0001,\"violence\":0.0001,\"violence/"
      "graphic\":0.0001},\"flagged\":false}]}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/moderations", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"input\":\"The weather is nice "
             "today.\",\"model\":\"omni-moderation-latest\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_moderation");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* Document reranking request routed through the proxy */
static void test_proxy_rerank(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"id\":\"rerank-proxy001\",\"meta\":{\"api_version\":{\"version\":"
      "\"2\"},\"billed_units\":{\"search_units\":1}},\"results\":[{\"index\":0,"
      "\"relevance_score\":0.95},{\"index\":1,\"relevance_score\":0.03}]}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/rerank", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"documents\":[\"Deep learning is a subset of machine learning "
             "using neural networks.\",\"The stock market closed higher "
             "today.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is deep "
             "learning?\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_proxy_rerank");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* 429 Too Many Requests from upstream provider through the proxy */
static void test_proxy_upstream_429(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"rate_limit_exceeded\",\"message\":\"Rate limit "
      "reached for gpt-4o in organization org-abc123 on tokens per min. Limit: "
      "10000, Used: 10000, Requested: 100. Please try again in "
      "600ms.\",\"param\":null,\"type\":\"requests\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],"
             "\"model\":\"openai/gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 429L, "test_proxy_upstream_429");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 500 Internal Server Error from upstream provider through the proxy */
static void test_proxy_upstream_500(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":null,\"message\":\"The server had an error while "
      "processing your request. Sorry about "
      "that!\",\"param\":null,\"type\":\"server_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],"
             "\"model\":\"openai/gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 500L, "test_proxy_upstream_500");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

int main(void) {
  test_proxy_auth_invalid();
  printf("PASS: 401 Unauthorized when an invalid API key is provided through "
         "the proxy\n");
  test_proxy_auth_missing();
  printf(
      "PASS: 401 Unauthorized when no API key is provided through the proxy\n");
  test_proxy_chat_basic();
  printf("PASS: Basic chat completion request routed through the proxy\n");
  test_proxy_chat_streaming();
  printf("PASS: Streaming chat completion routed through the proxy\n");
  test_proxy_embeddings();
  printf("PASS: Embedding request routed through the proxy\n");
  test_proxy_health();
  printf("PASS: Health check verifying proxy connectivity via list models\n");
  test_proxy_image_generate();
  printf("PASS: Image generation request routed through the proxy\n");
  test_proxy_models_list();
  printf("PASS: List models request routed through the proxy\n");
  test_proxy_moderation();
  printf("PASS: Content moderation request routed through the proxy\n");
  test_proxy_rerank();
  printf("PASS: Document reranking request routed through the proxy\n");
  test_proxy_upstream_429();
  printf(
      "PASS: 429 Too Many Requests from upstream provider through the proxy\n");
  test_proxy_upstream_500();
  printf("PASS: 500 Internal Server Error from upstream provider through the "
         "proxy\n");
  printf("All proxy tests passed.\n");
  return 0;
}
