/* Code generated by liter-llm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Verify all bindings expose the full API surface — constructor accepts all
 * config options and every method exists */
static void test_binding_api_parity(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{"
      "\"content\":\"OK\",\"role\":\"assistant\"}}],\"created\":1234567890,"
      "\"id\":\"chatcmpl-contract\",\"model\":\"gpt-4o\",\"object\":\"chat."
      "completion\",\"usage\":{\"completion_tokens\":1,\"prompt_tokens\":5,"
      "\"total_tokens\":6}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Contract "
             "test\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_binding_api_parity");
    liter_llm_assert_json_array_len(resp->body, "choices", 1,
                                    "test_binding_api_parity");
    liter_llm_assert_json_field(resp->body, "content", "OK",
                                "test_binding_api_parity");
    liter_llm_assert_json_field(resp->body, "model", "gpt-4o",
                                "test_binding_api_parity");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    liter_llm_assert_json_array_len(mock_body, "choices", 1,
                                    "test_binding_api_parity");
    liter_llm_assert_json_field(mock_body, "content", "OK",
                                "test_binding_api_parity");
    liter_llm_assert_json_field(mock_body, "model", "gpt-4o",
                                "test_binding_api_parity");
  }
}

/* Verify ocr() method exists in all bindings */
static void test_contract_ocr(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"model\":\"mistral/"
      "mistral-ocr-latest\",\"pages\":[{\"index\":0,\"markdown\":\"# Contract "
      "Test\\n\\nThis verifies OCR method exists.\"}]}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"document\":{\"type\":\"document_url\",\"url\":\"https://"
             "example.com/contract-test.pdf\"},\"model\":\"mistral/"
             "mistral-ocr-latest\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_contract_ocr");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

/* Verify search() method exists in all bindings */
static void test_contract_search(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"model\":\"brave/web-search\",\"results\":[{\"snippet\":\"Test "
      "result\",\"title\":\"Test\",\"url\":\"https://example.com\"}]}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url,
        "{\"model\":\"brave/web-search\",\"query\":\"contract test query\"}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 200L, "test_contract_search");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
  }
}

int main(void) {
  test_binding_api_parity();
  printf("PASS: Verify all bindings expose the full API surface — constructor "
         "accepts all config options and every method exists\n");
  test_contract_ocr();
  printf("PASS: Verify ocr() method exists in all bindings\n");
  test_contract_search();
  printf("PASS: Verify search() method exists in all bindings\n");
  printf("All contract tests passed.\n");
  return 0;
}
