/* Code generated by liter-llm-e2e-generator. DO NOT EDIT. */

#include "helpers.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Streaming chat completion via the Anthropic provider
 * (claude-3-5-sonnet-20241022) yielding multiple SSE chunks */
static void test_anthropic_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"max_tokens\":32,\"messages\":[{\"content\":\"Count to three, one "
        "word per "
        "response.\",\"role\":\"user\"}],\"model\":\"anthropic/"
        "claude-3-5-sonnet-20241022\",\"stream\":true}",
        chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_anthropic_stream]: expected >= 3 chunks, got %d\n",
              n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion via Azure OpenAI — verifies the azure/ prefix
 * routes correctly and SSE chunks are delivered in the standard OpenAI
 * chat.completion.chunk shape */
static void test_azure_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(url,
                               "{\"messages\":[{\"content\":\"Count to "
                               "3\",\"role\":\"user\"}],\"model\":\"azure/"
                               "gpt-4\",\"stream\":true,\"temperature\":0}",
                               chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_azure_stream]: expected >= 3 chunks, got %d\n", n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion that produces content across multiple SSE chunks */
static void test_basic_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Count to "
        "3\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}",
        chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_basic_stream]: expected >= 3 chunks, got %d\n", n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion via the AWS Bedrock provider using the bedrock/
 * prefix — verifies SSE chunks are yielded and assembled correctly from the
 * Converse streaming API */
static void test_bedrock_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"max_tokens\":32,\"messages\":[{\"content\":\"Count to three, one "
        "word per "
        "response.\",\"role\":\"user\"}],\"model\":\"bedrock/"
        "anthropic.claude-3-sonnet-20240229-v1:0\",\"stream\":true}",
        chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_bedrock_stream]: expected >= 3 chunks, got %d\n", n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion that produces no content chunks before the DONE
 * signal */
static void test_empty_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Say "
        "nothing\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}",
        chunks, 256);
    assert(n == 0);
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion via Ollama local provider with SSE chunks */
static void test_local_stream_ollama(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(url,
                               "{\"messages\":[{\"content\":\"Count to "
                               "3\",\"role\":\"user\"}],\"model\":\"ollama/"
                               "qwen2:0.5b\",\"stream\":true}",
                               chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_local_stream_ollama]: expected >= 3 chunks, got %d\n",
              n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Verify that the [DONE] sentinel signal properly terminates the stream */
static void test_stream_done_signal(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Say "
        "done\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true}",
        chunks, 256);
    if (n < 1) {
      fprintf(stderr,
              "FAIL [test_stream_done_signal]: expected >= 1 chunks, got %d\n",
              n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* 401 Unauthorized error on stream initiation before any chunks are received */
static void test_stream_error_401(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body =
      "{\"error\":{\"code\":\"invalid_api_key\",\"message\":\"Incorrect API "
      "key provided.\",\"param\":null,\"type\":\"invalid_request_error\"}}";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    LiterLlmResponse *resp = liter_llm_http_post(
        url, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],"
             "\"model\":\"gpt-4\",\"stream\":true}");
    assert(resp != NULL);
    liter_llm_assert_status(resp, 401L, "test_stream_error_401");
    liter_llm_response_free(resp);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion where the assistant responds with a tool call
 * across multiple chunks */
static void test_stream_with_tool_calls(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"What is the weather in "
        "NYC?\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true,"
        "\"tools\":[{\"function\":{\"description\":\"Get the current weather "
        "for a given "
        "location\",\"name\":\"get_weather\",\"parameters\":{\"properties\":{"
        "\"location\":{\"description\":\"The city and state, e.g. New York, "
        "NY\",\"type\":\"string\"}},\"required\":[\"location\"],\"type\":"
        "\"object\"}},\"type\":\"function\"}]}",
        chunks, 256);
    if (n < 1) {
      fprintf(
          stderr,
          "FAIL [test_stream_with_tool_calls]: expected >= 1 chunks, got %d\n",
          n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion that includes a usage summary in the final chunk */
static void test_stream_with_usage(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n = liter_llm_read_sse(
        url,
        "{\"messages\":[{\"content\":\"Say "
        "hi\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"stream\":true,\"stream_"
        "options\":{\"include_usage\":true}}",
        chunks, 256);
    if (n < 2) {
      fprintf(stderr,
              "FAIL [test_stream_with_usage]: expected >= 2 chunks, got %d\n",
              n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

/* Streaming chat completion via the Google Vertex AI provider using the
 * vertex_ai/ prefix — verifies SSE chunks from the Gemini streaming endpoint
 * are yielded and assembled correctly */
static void test_vertex_stream(void) {
  /* Pre-recorded mock response body. */
  const char *mock_body = "null";

  const char *base_url = getenv("LITER_LLM_TEST_BASE_URL");
  if (base_url != NULL) {
    /* Live HTTP test against a real server. */
    char url[1024];
    snprintf(url, sizeof(url), "%s/chat/completions", base_url);

    char *chunks[256];
    int n =
        liter_llm_read_sse(url,
                           "{\"max_tokens\":32,\"messages\":[{\"content\":"
                           "\"Count to three, one word per "
                           "response.\",\"role\":\"user\"}],\"model\":\"vertex_"
                           "ai/gemini-2.0-flash\",\"stream\":true}",
                           chunks, 256);
    if (n < 3) {
      fprintf(stderr,
              "FAIL [test_vertex_stream]: expected >= 3 chunks, got %d\n", n);
      abort();
    }
    for (int i = 0; i < n; i++)
      free(chunks[i]);
  } else {
    /* Offline: assert against pre-recorded mock body. */
    (void)mock_body; /* error or stream test — skip offline assertions */
  }
}

int main(void) {
  test_anthropic_stream();
  printf("PASS: Streaming chat completion via the Anthropic provider "
         "(claude-3-5-sonnet-20241022) yielding multiple SSE chunks\n");
  test_azure_stream();
  printf("PASS: Streaming chat completion via Azure OpenAI — verifies the "
         "azure/ prefix routes correctly and SSE chunks are delivered in the "
         "standard OpenAI chat.completion.chunk shape\n");
  test_basic_stream();
  printf("PASS: Streaming chat completion that produces content across "
         "multiple SSE chunks\n");
  test_bedrock_stream();
  printf("PASS: Streaming chat completion via the AWS Bedrock provider using "
         "the bedrock/ prefix — verifies SSE chunks are yielded and assembled "
         "correctly from the Converse streaming API\n");
  test_empty_stream();
  printf("PASS: Streaming chat completion that produces no content chunks "
         "before the DONE signal\n");
  test_local_stream_ollama();
  printf("PASS: Streaming chat completion via Ollama local provider with SSE "
         "chunks\n");
  test_stream_done_signal();
  printf("PASS: Verify that the [DONE] sentinel signal properly terminates the "
         "stream\n");
  test_stream_error_401();
  printf("PASS: 401 Unauthorized error on stream initiation before any chunks "
         "are received\n");
  test_stream_with_tool_calls();
  printf("PASS: Streaming chat completion where the assistant responds with a "
         "tool call across multiple chunks\n");
  test_stream_with_usage();
  printf("PASS: Streaming chat completion that includes a usage summary in the "
         "final chunk\n");
  test_vertex_stream();
  printf("PASS: Streaming chat completion via the Google Vertex AI provider "
         "using the vertex_ai/ prefix — verifies SSE chunks from the Gemini "
         "streaming endpoint are yielded and assembled correctly\n");
  printf("All streaming tests passed.\n");
  return 0;
}
