/* This file is auto-generated by alef. DO NOT EDIT. */
/* E2e tests for category: ocr */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "liter_llm.h"
#include "test_runner.h"

void test_ocr_url_document(void) {
    /* OCR request with a document URL input */
    LITERLLMOcrRequest* ocr_request_handle = literllm_ocr_request_from_json("{\"document\":{\"type\":\"document_url\",\"url\":\"https://example.com/doc.pdf\"},\"model\":\"mistral/mistral-ocr-latest\"}");
    assert(ocr_request_handle != NULL && "failed to build request");
    LITERLLMDefaultClient* client = literllm_create_client("test-key", NULL, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMOcrResponse* result = literllm_default_client_ocr(client, ocr_request_handle);
    assert(result != NULL && "expected call to succeed");
    literllm_ocr_response_free(result);
    literllm_ocr_request_free(ocr_request_handle);
    literllm_default_client_free(client);
}
