use std::fmt::Write as FmtWrite;

use anyhow::Result;
use camino::Utf8Path;

use crate::fixture::{Fixture, group_by_category};
use crate::generators::Generator;

pub struct PythonGenerator;

impl Generator for PythonGenerator {
    fn generate(&self, fixtures: &[Fixture], output_root: &Utf8Path) -> Result<()> {
        let py_dir = output_root.join("python");

        // Clean stale output before regenerating.
        let _ = std::fs::remove_dir_all(&py_dir);

        std::fs::create_dir_all(py_dir.join("tests"))
            .map_err(|e| anyhow::anyhow!("Failed to create python/tests dir: {e}"))?;

        write_pyproject_toml(&py_dir)?;
        write_tests_init(&py_dir)?;
        write_conftest(&py_dir)?;
        write_helpers(&py_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&py_dir, category, cat_fixtures)?;
        }

        // Run ruff check --fix + ruff format if available (best-effort; ignore errors).
        let _ = std::process::Command::new("uv")
            .args(["run", "ruff", "check", "--fix", "--quiet", "tests/"])
            .current_dir(&py_dir)
            .status();
        let _ = std::process::Command::new("uv")
            .args(["run", "ruff", "format", "--quiet", "tests/"])
            .current_dir(&py_dir)
            .status();

        println!("Generated Python e2e tests in {py_dir}");
        Ok(())
    }
}

// ─── File writers ─────────────────────────────────────────────────────────────

fn write_pyproject_toml(dir: &Utf8Path) -> Result<()> {
    let content = r#"# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "liter-lm-e2e-tests"
version = "0.1.0"
description = "Generated e2e tests for liter-lm Python binding"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "aiohttp>=3.9",
    "liter-lm",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
line-length = 120
"#;
    std::fs::write(dir.join("pyproject.toml"), content)
        .map_err(|e| anyhow::anyhow!("Failed to write pyproject.toml: {e}"))
}

fn write_tests_init(dir: &Utf8Path) -> Result<()> {
    let content = "# Code generated by liter-lm-e2e-generator. DO NOT EDIT.\n";
    std::fs::write(dir.join("tests").join("__init__.py"), content)
        .map_err(|e| anyhow::anyhow!("Failed to write tests/__init__.py: {e}"))
}

fn write_conftest(dir: &Utf8Path) -> Result<()> {
    // Write mock_server.py — importable module with MockRoute, MockServerInfo, handler
    let mock_server_content = r#"# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

import json
from typing import Any

from aiohttp import web


class MockServerInfo:
    """Holds the URL of a running mock aiohttp server."""

    def __init__(self, url: str) -> None:
        self.url = url


class MockRoute:
    """Configuration for a single mock HTTP route."""

    def __init__(
        self,
        path: str,
        method: str,
        status: int,
        body: Any = None,
        stream_chunks: list[Any] | None = None,
    ) -> None:
        self.path = path
        self.method = method.upper()
        self.status = status
        self.body = body or {}
        self.stream_chunks = stream_chunks or []


def make_handler(route: MockRoute):  # noqa: ANN202
    """Create an aiohttp handler for the given mock route."""
    async def handler(request: web.Request) -> web.Response:
        if route.stream_chunks:
            response = web.StreamResponse(
                status=route.status,
                headers={
                    "Content-Type": "text/event-stream",
                    "Cache-Control": "no-cache",
                },
            )
            await response.prepare(request)
            for chunk in route.stream_chunks:
                data = json.dumps(chunk) if not isinstance(chunk, str) else chunk
                await response.write(f"data: {data}\n\n".encode())
            await response.write(b"data: [DONE]\n\n")
            return response
        body = route.body if isinstance(route.body, str) else json.dumps(route.body)
        return web.Response(
            status=route.status,
            content_type="application/json",
            body=body,
        )

    return handler
"#;
    std::fs::write(dir.join("tests").join("mock_server.py"), mock_server_content)
        .map_err(|e| anyhow::anyhow!("Failed to write tests/mock_server.py: {e}"))?;

    // Write conftest.py — just the pytest fixture, imports from mock_server
    let conftest_content = r#"# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncGenerator

import pytest
from aiohttp import web

from .mock_server import MockRoute, MockServerInfo, make_handler


@pytest.fixture
async def mock_server(request: pytest.FixtureRequest) -> AsyncGenerator[MockServerInfo, None]:
    """Start a mock aiohttp server.

    Parameterize via ``@pytest.mark.parametrize`` or indirect fixture with a
    list of MockRoute instances passed through ``request.param``.
    """
    routes: list[MockRoute] = request.param if hasattr(request, "param") else []

    app = web.Application()
    for route in routes:
        method_lower = route.method.lower()
        router_method = getattr(app.router, f"add_{method_lower}", None)
        if router_method is not None:
            router_method(route.path, make_handler(route))

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, "127.0.0.1", 0)
    await site.start()

    port = site._server.sockets[0].getsockname()[1]  # type: ignore[union-attr]
    url = f"http://127.0.0.1:{port}"

    yield MockServerInfo(url)

    await runner.cleanup()
"#;
    std::fs::write(dir.join("tests").join("conftest.py"), conftest_content)
        .map_err(|e| anyhow::anyhow!("Failed to write tests/conftest.py: {e}"))
}

fn write_helpers(dir: &Utf8Path) -> Result<()> {
    let content = r#"# Code generated by liter-lm-e2e-generator. DO NOT EDIT.

from __future__ import annotations

from typing import Any

import pytest


def assert_choices_count(response: Any, expected: int) -> None:
    """Assert the number of choices in a chat completion response."""
    actual = len(response.choices)
    if actual != expected:
        pytest.fail(f"Expected {expected} choice(s), got {actual}")


def assert_first_choice_content(response: Any, expected: str) -> None:
    """Assert the content of the first choice message."""
    actual = response.choices[0].message.content
    if actual != expected:
        pytest.fail(f"Expected first choice content {expected!r}, got {actual!r}")


def assert_usage(response: Any, field: str, expected: int) -> None:
    """Assert a specific usage field value."""
    usage = response.usage
    if usage is None:
        pytest.fail("Expected usage object but got None")
    actual = getattr(usage, field, None)
    if actual != expected:
        pytest.fail(f"Expected usage.{field} == {expected}, got {actual}")


def assert_model(response: Any, expected: str) -> None:
    """Assert the model identifier in the response."""
    actual = response.model
    if actual != expected:
        pytest.fail(f"Expected model {expected!r}, got {actual!r}")


def assert_error_type(error: Exception, expected: str) -> None:
    """Assert the error class name matches expected."""
    actual = type(error).__name__
    if actual != expected:
        pytest.fail(f"Expected error type {expected!r}, got {actual!r}")


def assert_stream_chunks(chunks: list[Any], min_count: int) -> None:
    """Assert a minimum number of stream chunks were received."""
    actual = len(chunks)
    if actual < min_count:
        pytest.fail(f"Expected at least {min_count} stream chunk(s), got {actual}")
"#;
    std::fs::write(dir.join("tests").join("helpers.py"), content)
        .map_err(|e| anyhow::anyhow!("Failed to write tests/helpers.py: {e}"))
}

// ─── Test file generation ─────────────────────────────────────────────────────

fn write_test_file(dir: &Utf8Path, category: &str, fixtures: &[&Fixture]) -> Result<()> {
    let mut out = String::new();

    writeln!(out, "# Code generated by liter-lm-e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "from __future__ import annotations").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import pytest").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "from .mock_server import MockRoute, MockServerInfo").unwrap();

    // Check if any fixture in this category uses error assertions.
    let has_errors = fixtures
        .iter()
        .any(|f| f.api.mock_response.status >= 400 || !f.assertions.expect_success);

    if has_errors {
        writeln!(out, "from liter_lm import (  # noqa: E402").unwrap();
        writeln!(out, "    LlmClient,").unwrap();
        writeln!(out, "    AuthenticationError,").unwrap();
        writeln!(out, "    RateLimitedError,").unwrap();
        writeln!(out, "    ServerError,").unwrap();
        writeln!(out, "    NotFoundError,").unwrap();
        writeln!(out, "    ServiceUnavailableError,").unwrap();
        writeln!(out, "    BadRequestError,").unwrap();
        writeln!(out, ")").unwrap();
    } else {
        writeln!(out, "from liter_lm import LlmClient  # noqa: E402").unwrap();
    }

    writeln!(out).unwrap();

    for fixture in fixtures {
        if fixture.skip.languages.iter().any(|l| l == "python") {
            continue;
        }
        write_test_fn(&mut out, fixture);
    }

    let out = out.trim_end().to_string() + "\n";

    let filename = format!("test_{}.py", sanitize_name(category));
    let path = dir.join("tests").join(&filename);
    std::fs::write(&path, &out).map_err(|e| anyhow::anyhow!("Failed to write {filename}: {e}"))
}

fn write_test_fn(out: &mut String, fixture: &Fixture) {
    let fn_name = sanitize_name(&fixture.id);
    let method = fixture.api.method.as_str();
    let endpoint = endpoint_for_method(method);
    let http_method = match method {
        "list_models" | "retrieve_file" | "list_files" | "file_content" | "retrieve_batch" | "list_batches"
        | "retrieve_response" => "GET",
        "delete_file" | "cancel_batch" | "cancel_response" => "POST",
        _ => "POST",
    };
    let status = fixture.api.mock_response.status;

    writeln!(out).unwrap();
    writeln!(out, "@pytest.mark.asyncio").unwrap();

    // Build the mock_server parametrize decorator.
    let body_json = serde_json::to_string(&fixture.api.mock_response.body).unwrap_or_default();

    if fixture.api.mock_response.stream_chunks.is_empty() {
        writeln!(out, "@pytest.mark.parametrize(\"mock_server\", [[").unwrap();
        writeln!(
            out,
            "    MockRoute({endpoint:?}, {http_method:?}, {status}, {body_json:?}),"
        )
        .unwrap();
        writeln!(out, "]], indirect=True)").unwrap();
    } else {
        writeln!(out, "@pytest.mark.parametrize(\"mock_server\", [[").unwrap();
        writeln!(out, "    MockRoute(").unwrap();
        writeln!(out, "        {endpoint:?},").unwrap();
        writeln!(out, "        {http_method:?},").unwrap();
        writeln!(out, "        {status},").unwrap();
        writeln!(out, "        stream_chunks=[").unwrap();
        for chunk in &fixture.api.mock_response.stream_chunks {
            let chunk_json = serde_json::to_string(chunk).unwrap_or_default();
            writeln!(out, "            {chunk_json:?},").unwrap();
        }
        writeln!(out, "        ],").unwrap();
        writeln!(out, "    ),").unwrap();
        writeln!(out, "]], indirect=True)").unwrap();
    }

    writeln!(out, "async def test_{fn_name}(mock_server: MockServerInfo) -> None:").unwrap();
    writeln!(out, "    \"\"\"{}\"\"\"", fixture.description).unwrap();

    match method {
        "chat" => emit_chat_test(out, fixture),
        "chat_stream" => emit_stream_test(out, fixture),
        "embed" => emit_embed_test(out, fixture),
        "list_models" => emit_list_models_test(out, fixture),
        other => {
            writeln!(out, "    # TODO: unknown method {other:?}").unwrap();
        }
    }

    writeln!(out).unwrap();
}

// ─── API call + assertion emission ────────────────────────────────────────────

fn emit_chat_test(out: &mut String, fixture: &Fixture) {
    let req_json = serde_json::to_string(&fixture.api.request).unwrap_or_default();
    let is_error = fixture.api.mock_response.status >= 400 || !fixture.assertions.expect_success;

    writeln!(out, "    import json").unwrap();
    writeln!(
        out,
        "    client = LlmClient(api_key=\"test-key\", base_url=mock_server.url, max_retries=0)"
    )
    .unwrap();
    writeln!(out, "    request = json.loads({req_json:?})").unwrap();

    if is_error {
        let exc_class = error_exception_class(fixture.api.mock_response.status);
        writeln!(out, "    with pytest.raises({exc_class}):").unwrap();
        writeln!(out, "        await client.chat(**request)").unwrap();
    } else {
        writeln!(out, "    response = await client.chat(**request)").unwrap();
        emit_chat_assertions(out, fixture);
    }
}

fn emit_stream_test(out: &mut String, fixture: &Fixture) {
    let req_json = serde_json::to_string(&fixture.api.request).unwrap_or_default();
    let is_error = fixture.api.mock_response.status >= 400 || !fixture.assertions.expect_success;

    writeln!(out, "    import json").unwrap();
    writeln!(
        out,
        "    client = LlmClient(api_key=\"test-key\", base_url=mock_server.url, max_retries=0)"
    )
    .unwrap();
    writeln!(out, "    request = json.loads({req_json:?})").unwrap();

    if is_error {
        let exc_class = error_exception_class(fixture.api.mock_response.status);
        writeln!(out, "    with pytest.raises({exc_class}):").unwrap();
        writeln!(out, "        async for _ in await client.chat_stream(**request):").unwrap();
        writeln!(out, "            pass").unwrap();
        return;
    }

    writeln!(out, "    chunks = []").unwrap();
    writeln!(out, "    async for chunk in await client.chat_stream(**request):").unwrap();
    writeln!(out, "        chunks.append(chunk)").unwrap();

    // Determine minimum meaningful chunks.
    let meaningful: usize = fixture
        .api
        .mock_response
        .stream_chunks
        .iter()
        .filter(|c| {
            c.get("choices")
                .and_then(|ch| ch.as_array())
                .and_then(|arr| arr.first())
                .and_then(|ch| ch.get("delta"))
                .and_then(|d| d.get("content"))
                .and_then(|v| v.as_str())
                .is_some_and(|s| !s.is_empty())
        })
        .count();

    if fixture.api.mock_response.stream_chunks.is_empty() {
        writeln!(
            out,
            "    assert len(chunks) == 0, f\"Expected 0 chunks for empty stream, got {{len(chunks)}}\""
        )
        .unwrap();
    } else {
        let min_chunks = meaningful.max(1);
        writeln!(
            out,
            "    assert len(chunks) >= {min_chunks}, f\"Expected at least {min_chunks} chunk(s), got {{len(chunks)}}\""
        )
        .unwrap();
    }

    // Concatenated content assertion.
    let expected_content: String = fixture
        .api
        .mock_response
        .stream_chunks
        .iter()
        .filter_map(|c| {
            c.get("choices")
                .and_then(|ch| ch.as_array())
                .and_then(|arr| arr.first())
                .and_then(|ch| ch.get("delta"))
                .and_then(|d| d.get("content"))
                .and_then(|v| v.as_str())
                .map(str::to_owned)
        })
        .collect();

    if !expected_content.is_empty() {
        writeln!(
            out,
            "    content = \"\".join(c.choices[0].delta.content or \"\" for c in chunks if c.choices)"
        )
        .unwrap();
        writeln!(
            out,
            "    assert content == {expected_content:?}, f\"Stream content mismatch: {{content!r}}\""
        )
        .unwrap();
    }
}

fn emit_embed_test(out: &mut String, fixture: &Fixture) {
    let req_json = serde_json::to_string(&fixture.api.request).unwrap_or_default();
    let is_error = fixture.api.mock_response.status >= 400 || !fixture.assertions.expect_success;

    writeln!(out, "    import json").unwrap();
    writeln!(
        out,
        "    client = LlmClient(api_key=\"test-key\", base_url=mock_server.url, max_retries=0)"
    )
    .unwrap();
    writeln!(out, "    request = json.loads({req_json:?})").unwrap();

    if is_error {
        let exc_class = error_exception_class(fixture.api.mock_response.status);
        writeln!(out, "    with pytest.raises({exc_class}):").unwrap();
        writeln!(out, "        await client.embed(**request)").unwrap();
        return;
    }

    writeln!(out, "    response = await client.embed(**request)").unwrap();
    writeln!(out).unwrap();

    // Derive from mock response body.
    if let Some(data_arr) = fixture.api.mock_response.body.get("data").and_then(|v| v.as_array()) {
        let count = data_arr.len();
        writeln!(
            out,
            "    assert len(response.data) == {count}, f\"Expected {count} embedding(s), got {{len(response.data)}}\""
        )
        .unwrap();

        if let Some(first_embedding) = data_arr
            .first()
            .and_then(|e| e.get("embedding"))
            .and_then(|v| v.as_array())
        {
            let dims = first_embedding.len();
            if dims > 0 {
                writeln!(
                    out,
                    "    assert len(response.data[0].embedding) == {dims}, f\"Expected {dims} dimensions, got {{len(response.data[0].embedding)}}\""
                )
                .unwrap();
            }
        }
    }

    if let Some(min_embed) = fixture.assertions.embedding_count {
        writeln!(
            out,
            "    assert len(response.data) >= {min_embed}, f\"Expected at least {min_embed} embedding(s), got {{len(response.data)}}\""
        )
        .unwrap();
    }
}

fn emit_list_models_test(out: &mut String, fixture: &Fixture) {
    let is_error = fixture.api.mock_response.status >= 400 || !fixture.assertions.expect_success;

    writeln!(
        out,
        "    client = LlmClient(api_key=\"test-key\", base_url=mock_server.url, max_retries=0)"
    )
    .unwrap();

    if is_error {
        let exc_class = error_exception_class(fixture.api.mock_response.status);
        writeln!(out, "    with pytest.raises({exc_class}):").unwrap();
        writeln!(out, "        await client.list_models()").unwrap();
        return;
    }

    writeln!(out, "    response = await client.list_models()").unwrap();
    writeln!(out).unwrap();

    if let Some(data_arr) = fixture.api.mock_response.body.get("data").and_then(|v| v.as_array()) {
        let count = data_arr.len();
        writeln!(
            out,
            "    assert len(response.data) == {count}, f\"Expected {count} model(s), got {{len(response.data)}}\""
        )
        .unwrap();
    }

    if let Some(min_models) = fixture.assertions.models_count_min {
        writeln!(
            out,
            "    assert len(response.data) >= {min_models}, f\"Expected at least {min_models} model(s), got {{len(response.data)}}\""
        )
        .unwrap();
    }
}

// ─── Chat assertion helpers ────────────────────────────────────────────────────

fn emit_chat_assertions(out: &mut String, fixture: &Fixture) {
    writeln!(out).unwrap();

    // choices count from mock response body.
    if let Some(choices_arr) = fixture.api.mock_response.body.get("choices").and_then(|v| v.as_array()) {
        let count = choices_arr.len();
        writeln!(
            out,
            "    assert len(response.choices) == {count}, f\"Expected {count} choice(s), got {{len(response.choices)}}\""
        )
        .unwrap();

        if let Some(first_choice) = choices_arr.first() {
            // message content
            if let Some(content) = first_choice
                .get("message")
                .and_then(|m| m.get("content"))
                .and_then(|c| c.as_str())
            {
                writeln!(
                    out,
                    "    assert response.choices[0].message.content == {content:?}, \"message content mismatch\""
                )
                .unwrap();
            }

            // finish_reason
            if let Some(fr) = first_choice
                .get("finish_reason")
                .and_then(|v| v.as_str())
                .filter(|s| !s.is_empty())
            {
                writeln!(
                    out,
                    "    assert response.choices[0].finish_reason == {fr:?}, \"finish_reason mismatch\""
                )
                .unwrap();
            }

            // tool_calls presence
            if first_choice
                .get("message")
                .and_then(|m| m.get("tool_calls"))
                .and_then(|t| t.as_array())
                .is_some_and(|arr| !arr.is_empty())
            {
                writeln!(
                    out,
                    "    assert response.choices[0].message.tool_calls, \"Expected tool_calls\""
                )
                .unwrap();

                if let Some(fn_name) = first_choice
                    .get("message")
                    .and_then(|m| m.get("tool_calls"))
                    .and_then(|t| t.as_array())
                    .and_then(|arr| arr.first())
                    .and_then(|tc| tc.get("function"))
                    .and_then(|f| f.get("name"))
                    .and_then(|n| n.as_str())
                {
                    writeln!(
                        out,
                        "    assert response.choices[0].message.tool_calls[0].function.name == {fn_name:?}, \"tool call function name mismatch\""
                    )
                    .unwrap();
                }
            }
        }
    }

    // usage
    if let Some(usage) = fixture.api.mock_response.body.get("usage").filter(|v| !v.is_null()) {
        writeln!(out, "    assert response.usage is not None, \"Expected usage object\"").unwrap();
        if let Some(total) = usage.get("total_tokens").and_then(|v| v.as_u64()) {
            writeln!(
                out,
                "    assert response.usage.total_tokens == {total}, \"total_tokens mismatch\""
            )
            .unwrap();
        }
    }

    // model
    let model = fixture
        .assertions
        .model
        .as_deref()
        .or_else(|| fixture.api.mock_response.body.get("model").and_then(|v| v.as_str()));
    if let Some(model) = model {
        writeln!(out, "    assert response.model == {model:?}, \"model mismatch\"").unwrap();
    }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

fn endpoint_for_method(method: &str) -> &'static str {
    match method {
        "chat" | "chat_stream" => "/chat/completions",
        "embed" => "/embeddings",
        "list_models" => "/models",
        "image_generate" => "/images/generations",
        "speech" => "/audio/speech",
        "transcribe" => "/audio/transcriptions",
        "moderate" => "/moderations",
        "rerank" => "/rerank",
        "create_file" | "list_files" => "/files",
        "retrieve_file" | "delete_file" => "/files/file-placeholder",
        "file_content" => "/files/file-placeholder/content",
        "create_batch" | "list_batches" => "/batches",
        "retrieve_batch" | "cancel_batch" => "/batches/batch-placeholder",
        "create_response" => "/responses",
        "retrieve_response" | "cancel_response" => "/responses/resp-placeholder",
        _ => "/chat/completions",
    }
}

fn error_exception_class(status: u16) -> &'static str {
    match status {
        401 => "AuthenticationError",
        429 => "RateLimitedError",
        400 => "BadRequestError",
        404 => "NotFoundError",
        500 => "ServerError",
        502 | 503 => "ServiceUnavailableError",
        _ => "Exception",
    }
}

fn sanitize_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .to_lowercase()
}
