#!/usr/bin/env bash
# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: search
set -euo pipefail

test_search_basic() {
    # Basic web search request with a simple query
    local output
    output=$(liter_llm chat)

}

run_tests_search() {
    run_test test_search_basic
}
