// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

package literllm_e2e

import (
	"bytes"
	"encoding/json"
	"net/http"
	"testing"
)

func TestConfiguration(t *testing.T) {
	t.Run("custom_base_url", func(t *testing.T) {
		// Client configured with a custom base URL routes all requests to that endpoint
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       200,
				Body:         `{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-local-001","model":"local-model","object":"chat.completion","usage":{"completion_tokens":4,"prompt_tokens":3,"total_tokens":7}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"local-model\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertEqual(t, "status code", 200, resp.StatusCode)

		var result map[string]interface{}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			t.Fatalf("decode response: %v", err)
		}

		choices, _ := result["choices"].([]interface{})
		AssertEqual(t, "choices count", 1, len(choices))

		if len(choices) > 0 {
			choice, _ := choices[0].(map[string]interface{})
			message, _ := choice["message"].(map[string]interface{})
			AssertEqual(t, "first choice content", "Hi there!", message["content"])
		}
		AssertEqual(t, "model", "local-model", result["model"])

		usage, _ := result["usage"].(map[string]interface{})
		AssertTrue(t, "usage not nil", usage != nil)
		AssertEqual(t, "total_tokens", float64(7), usage["total_tokens"])
	})

	t.Run("extra_headers", func(t *testing.T) {
		// Client configured with extra custom headers successfully completes a chat request
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       200,
				Body:         `{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you?","role":"assistant"}}],"created":1711000140,"id":"chatcmpl-headers001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":8,"total_tokens":16}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertEqual(t, "status code", 200, resp.StatusCode)

		var result map[string]interface{}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			t.Fatalf("decode response: %v", err)
		}

		choices, _ := result["choices"].([]interface{})
		AssertEqual(t, "choices count", 1, len(choices))

		if len(choices) > 0 {
			choice, _ := choices[0].(map[string]interface{})
			message, _ := choice["message"].(map[string]interface{})
			AssertEqual(t, "first choice content", "Hello! How can I help you?", message["content"])
		}
		AssertEqual(t, "model", "gpt-4", result["model"])

		usage, _ := result["usage"].(map[string]interface{})
		AssertTrue(t, "usage not nil", usage != nil)
		AssertEqual(t, "total_tokens", float64(16), usage["total_tokens"])
	})

}
