// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

package literllm_e2e

import (
	"bytes"
	"fmt"
	"net/http"
	"testing"
)

func TestErrorHandling(t *testing.T) {
	t.Run("anthropic_error_auth", func(t *testing.T) {
		// 401 Authentication error returned by the Anthropic API when the API key is invalid
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       401,
				Body:         `{"error":{"message":"invalid x-api-key","type":"authentication_error"},"type":"error"}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"anthropic/claude-3-5-sonnet-20241022\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 401, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("auth_401", func(t *testing.T) {
		// 401 Unauthorized error when API key is invalid or missing
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       401,
				Body:         `{"error":{"code":"invalid_api_key","message":"Incorrect API key provided. You can find your API key at https://platform.openai.com/account/api-keys.","param":null,"type":"invalid_request_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 401, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("azure_error_auth", func(t *testing.T) {
		// Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       401,
				Body:         `{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.","param":null,"type":"invalid_request_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"azure/gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 401, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("bad_request_400", func(t *testing.T) {
		// 400 Bad Request error when a parameter value is invalid
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       400,
				Body:         `{"error":{"message":"Invalid parameter: temperature must be between 0 and 2","type":"invalid_request_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\",\"temperature\":5.0}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 400, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("content_policy_violation", func(t *testing.T) {
		// 400 error when a request is rejected due to content policy
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       400,
				Body:         `{"error":{"message":"Your request was rejected as a result of our content_policy","type":"invalid_request_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Generate harmful content\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 400, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("context_window_exceeded", func(t *testing.T) {
		// 400 error when the prompt exceeds the model's maximum context length
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       400,
				Body:         `{"error":{"code":"context_length_exceeded","message":"This model's maximum context length is 8192 tokens","type":"invalid_request_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Very long prompt that exceeds the context window...\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 400, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("forbidden_403", func(t *testing.T) {
		// 403 Forbidden error when the API key does not have access to the requested resource
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       403,
				Body:         `{"error":{"message":"Access denied","type":"access_denied"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 403, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("gateway_timeout_504", func(t *testing.T) {
		// 504 Gateway Timeout error when the upstream service times out
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       504,
				Body:         `{"error":{"message":"Gateway timeout","type":"server_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 504, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("not_found_404", func(t *testing.T) {
		// 404 Not Found error when requesting a model that does not exist
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       404,
				Body:         `{"error":{"message":"Model not found","type":"not_found_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-99\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 404, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("rate_limit_429", func(t *testing.T) {
		// 429 Too Many Requests error when the rate limit is exceeded
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       429,
				Body:         `{"error":{"code":"rate_limit_exceeded","message":"Rate limit reached for gpt-4 in organization org-abc123 on tokens per min. Limit: 10000, Used: 10000, Requested: 100. Please try again in 600ms.","param":null,"type":"requests"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 429, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("server_error_500", func(t *testing.T) {
		// 500 Internal Server Error from the upstream API
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       500,
				Body:         `{"error":{"code":null,"message":"The server had an error while processing your request. Sorry about that!","param":null,"type":"server_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 500, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

	t.Run("service_unavailable_502", func(t *testing.T) {
		// 502 Bad Gateway error when the upstream service is unavailable
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       502,
				Body:         `{"error":{"message":"Bad gateway","type":"server_error"}}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		reqBody := bytes.NewBufferString("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
		resp, err := http.Post(server.URL+"/chat/completions", "application/json", reqBody)
		if err != nil {
			t.Fatalf("http.Post failed: %v", err)
		}
		defer resp.Body.Close()

		AssertTrue(t, "expected error status", resp.StatusCode >= 400)
		AssertEqual(t, "error status code", 502, resp.StatusCode)
		_ = fmt.Sprintf("") // suppress import
	})

}
