// Code generated by liter-llm-e2e-generator. DO NOT EDIT.

package literllm_e2e

import (
	"testing"
)

func TestOcr(t *testing.T) {
	t.Run("ocr_url_document", func(t *testing.T) {
		// OCR request with a document URL input
		server := NewMockServer([]MockRoute{
			{
				Path:         "/chat/completions",
				Method:       "POST",
				Status:       200,
				Body:         `{"model":"mistral/mistral-ocr-latest","pages":[{"index":0,"markdown":"# Test Document\n\nThis is a test."}]}`,
				StreamChunks: nil,
			},
		})
		defer server.Close()

		// TODO: unknown method "ocr"
	})

}
