// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: transcribe

use liter_llm::chat;
mod mock_server;
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_edge_transcribe_empty_audio() {
    // Transcription of a silent or empty audio file returns empty text
    let mock_route = MockRoute {
        path: "/v1/audio/transcriptions",
        method: "POST",
        status: 200,
        body: r#"{"text":""}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    assert!(format!("{:?}", result.text).contains(r#""#), "expected to contain: {}", r#""#);
}

#[tokio::test]
async fn test_error_transcribe_auth_401() {
    // 401 Unauthorized for transcription with invalid API key
    let mock_route = MockRoute {
        path: "/v1/audio/transcriptions",
        method: "POST",
        status: 401,
        body: r#"{"error":{"code":"invalid_api_key","message":"Incorrect API key provided.","param":null,"type":"invalid_request_error"}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await;
    assert!(result.is_err(), "expected call to fail");
    assert!(result.as_ref().unwrap_err().to_string().contains("Authentication"), "error message mismatch");
}

#[tokio::test]
async fn test_error_transcribe_bad_format() {
    // 400 Bad Request when audio format is unsupported
    let mock_route = MockRoute {
        path: "/v1/audio/transcriptions",
        method: "POST",
        status: 400,
        body: r#"{"error":{"code":null,"message":"Invalid file format. Supported formats: flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, webm.","param":"file","type":"invalid_request_error"}}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await;
    assert!(result.is_err(), "expected call to fail");
    assert!(result.as_ref().unwrap_err().to_string().contains("InvalidRequest"), "error message mismatch");
}

#[tokio::test]
async fn test_smoke_transcribe_basic() {
    // Basic audio transcription
    let mock_route = MockRoute {
        path: "/v1/audio/transcriptions",
        method: "POST",
        status: 200,
        body: r#"{"text":"Hello, this is a test transcription."}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    assert!(format!("{:?}", result.text).contains(r#"Hello, this is a test transcription."#), "expected to contain: {}", r#"Hello, this is a test transcription."#);
}

#[tokio::test]
async fn test_smoke_transcribe_with_language() {
    // Audio transcription with explicit language hint
    let mock_route = MockRoute {
        path: "/v1/audio/transcriptions",
        method: "POST",
        status: 200,
        body: r#"{"text":"Hallo, dies ist ein Testtranskription."}"#.to_string(),
        stream_chunks: vec![],
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json = serde_json::json!(null);
    let request = serde_json::from_value(request_json).unwrap();
    let result = chat(request).await.expect("should succeed");
    assert!(format!("{:?}", result.text).contains(r#"Hallo, dies ist ein Testtranskription."#), "expected to contain: {}", r#"Hallo, dies ist ein Testtranskription."#);
}

